// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum_e_logic_tag.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from enum_e_logic_tag.proto</summary>
  public static partial class EnumELogicTagReflection {

    #region Descriptor
    /// <summary>File descriptor for enum_e_logic_tag.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumELogicTagReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZlbnVtX2VfbG9naWNfdGFnLnByb3RvEgZ6cHJvdG8qlwIKCUVMb2dpY1Rh",
            "ZxIQCgxMb2dpY1RhZ05vbmUQABIVChFMb2dpY1RhZ0NvcmVTa2lsbBADEhUK",
            "EUxvZ2ljVGFnQmFzZVNraWxsEAQSFgoSTG9naWNUYWdGaW5hbFNraWxsEAUS",
            "DgoKTG9naWNUYWdVUBAPEhIKDkxvZ2ljVGFnU2hpZWxkEBoSHAoYTG9naWNU",
            "YWdIYXJkQ3Jvd2RDb250cm9sEEASGgoWTG9naWNUYWdEYW1hZ2VQaHlzaWNh",
            "bBBCEhkKFUxvZ2ljVGFnRGFtYWdlTWFnaWNhbBBDEhEKDExvZ2ljVGFnSGVh",
            "bBDrBxIRCgxMb2dpY1RhZ0J1ZmYQ7AcSEwoOTG9naWNUYWdEZWJ1ZmYQ7Qdi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zproto.ELogicTag), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ELogicTag {
    [pbr::OriginalName("LogicTagNone")] LogicTagNone = 0,
    [pbr::OriginalName("LogicTagCoreSkill")] LogicTagCoreSkill = 3,
    [pbr::OriginalName("LogicTagBaseSkill")] LogicTagBaseSkill = 4,
    [pbr::OriginalName("LogicTagFinalSkill")] LogicTagFinalSkill = 5,
    [pbr::OriginalName("LogicTagUP")] LogicTagUp = 15,
    [pbr::OriginalName("LogicTagShield")] LogicTagShield = 26,
    [pbr::OriginalName("LogicTagHardCrowdControl")] LogicTagHardCrowdControl = 64,
    [pbr::OriginalName("LogicTagDamagePhysical")] LogicTagDamagePhysical = 66,
    [pbr::OriginalName("LogicTagDamageMagical")] LogicTagDamageMagical = 67,
    [pbr::OriginalName("LogicTagHeal")] LogicTagHeal = 1003,
    [pbr::OriginalName("LogicTagBuff")] LogicTagBuff = 1004,
    [pbr::OriginalName("LogicTagDebuff")] LogicTagDebuff = 1005,
  }

  #endregion

}

#endregion Designer generated code
