// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum_e_community_authority_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from enum_e_community_authority_type.proto</summary>
  public static partial class EnumECommunityAuthorityTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for enum_e_community_authority_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumECommunityAuthorityTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVlbnVtX2VfY29tbXVuaXR5X2F1dGhvcml0eV90eXBlLnByb3RvEgZ6cHJv",
            "dG8qfgoXRUNvbW11bml0eUF1dGhvcml0eVR5cGUSGgoWQ29tbXVuaXR5QXV0",
            "aG9yaXR5VHlwZRAAEiMKH0NvbW11bml0eUF1dGhvcml0eVR5cGVXYXJlSG91",
            "c2UQARIiCh5Db21tdW5pdHlBdXRob3JpdHlUeXBlU2VsbEl0ZW0QAmIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zproto.ECommunityAuthorityType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ECommunityAuthorityType {
    [pbr::OriginalName("CommunityAuthorityType")] CommunityAuthorityType = 0,
    [pbr::OriginalName("CommunityAuthorityTypeWareHouse")] CommunityAuthorityTypeWareHouse = 1,
    [pbr::OriginalName("CommunityAuthorityTypeSellItem")] CommunityAuthorityTypeSellItem = 2,
  }

  #endregion

}

#endregion Designer generated code
