// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum_e_ride_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from enum_e_ride_type.proto</summary>
  public static partial class EnumERideTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for enum_e_ride_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumERideTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZlbnVtX2VfcmlkZV90eXBlLnByb3RvEgZ6cHJvdG8qXQoJRVJpZGVUeXBl",
            "EhIKDlJpZGVUeXBlTm9ybWFsEAASEQoNUmlkZVR5cGVSaWRlchABEhMKD1Jp",
            "ZGVUeXBlVmVoaWNsZRACEhQKEFJpZGVUeXBlUGxhdGZvcm0QA2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zproto.ERideType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ERideType {
    [pbr::OriginalName("RideTypeNormal")] RideTypeNormal = 0,
    [pbr::OriginalName("RideTypeRider")] RideTypeRider = 1,
    [pbr::OriginalName("RideTypeVehicle")] RideTypeVehicle = 2,
    [pbr::OriginalName("RideTypePlatform")] RideTypePlatform = 3,
  }

  #endregion

}

#endregion Designer generated code
