// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum_text_check_scene_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from enum_text_check_scene_type.proto</summary>
  public static partial class EnumTextCheckSceneTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for enum_text_check_scene_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumTextCheckSceneTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBlbnVtX3RleHRfY2hlY2tfc2NlbmVfdHlwZS5wcm90bxIGenByb3RvKtIL",
            "ChJUZXh0Q2hlY2tTY2VuZVR5cGUSEgoOVGV4dENoZWNrRXJyb3IQABIbChdU",
            "ZXh0Q2hlY2tDcmVhdGVSb2xlTmFtZRBlEhwKGFRleHRDaGVja0NyZWF0ZVVu",
            "aW9uTmFtZRBmEhsKF1RleHRDaGVja1VuaW9uTWFuaWZlc3RvEGcSGQoVVGV4",
            "dENoZWNrVW5pb25Kb2JOYW1lEGgSGQoVVGV4dENoZWNrVW5pb25SZWNydWl0",
            "EGkSJAogVGV4dENoZWNrVW5pb25SZWNydWl0RGVzY3JpcHRpb24QahIaChZU",
            "ZXh0Q2hlY2tNYXBDdXN0b21GbGFnEGwSFgoSVGV4dENoZWNrQWxidW1OYW1l",
            "EG0SFwoTVGV4dENoZWNrQ2hhbmdlTmFtZRBuEhwKGFRleHRDaGVja1VuaW9u",
            "Q2hhbmdlTmFtZRBvEhsKF1RleHRDaGVja0FsYnVtVXBsb2FkVG1wEHASHwob",
            "VGV4dENoZWNrQWxidW1QaG90b0VkaXRUZXh0EHESIQodVGV4dENoZWNrQWxi",
            "dW1QaG90b0VkaXRVcGxvYWQQchIdChlUZXh0Q2hlY2tBbGJ1bVVwbG9hZFBo",
            "b3RvEHMSHAoYVGV4dENoZWNrVW5pb25VcGxvYWRIZWFkEHQSHAoYVGV4dENo",
            "ZWNrVW5pb25VcGxvYWRDYXJkEHUSHAoYVGV4dENoZWNrQWxidW1DaGFuZ2VO",
            "YW1lEHYSJAogVGV4dENoZWNrQ29tbXVuaXR5Q2hlY2tJbnRyb2R1Y2UQdxIh",
            "Ch1UZXh0Q2hlY2tDb21tdW5pdHlDaGVja0ludml0ZRB4EicKI1RleHRDaGVj",
            "a0NvbW11bml0eUNoZWNrTGlnaHRpbmdOYW1lEHkSMwovVGV4dENoZWNrQ29t",
            "bXVuaXR5Q2hlY2tDb21iaW5hdGlvbkZ1cm5pdHVyZU5hbWUQehIkCiBUZXh0",
            "Q2hlY2tDb21tdW5pdHlDaGVja1Bob3RvTmFtZRB7Eh8KG1RleHRDaGVja0Nv",
            "bW11bml0eUNoZWNrTmFtZRB8EhsKF1RleHRDaGVja1VuaW9uQWxidW1OYW1l",
            "EH0SIQodVGV4dENoZWNrQ2hhbmdlVW5pb25BbGJ1bU5hbWUQfhIgChxUZXh0",
            "Q2hlY2tDaGFuZ2VNYXBDdXN0b21GbGFnEH8SIAobVGV4dENoZWNrQ2hhbmdl",
            "VW5pb25SZWNydWl0EIABEisKJlRleHRDaGVja0NoYW5nZVVuaW9uUmVjcnVp",
            "dERlc2NyaXB0aW9uEIEBEiMKHlRleHRDaGVja1VuaW9uQWxidW1VcGxvYWRQ",
            "aG90bxCCARIeChlUZXh0Q2hlY2tDaGF0V29ybGRDaGFubmVsEOkHEh4KGVRl",
            "eHRDaGVja0NoYXRVbmlvbkNoYW5uZWwQ6gcSHQoYVGV4dENoZWNrQ2hhdFRl",
            "YW1DaGFubmVsEOsHEiAKG1RleHRDaGVja0NoYXRQcml2YXRlQ2hhbm5lbBDt",
            "BxIeChlUZXh0Q2hlY2tDaGF0U2NlbmVDaGFubmVsEO4HEhoKFVRleHRDaGVj",
            "a0ZyaWVuZFJlbWFyaxDRDxIcChdUZXh0Q2hlY2tUZWFtVGFyZ2V0SW5mbxDS",
            "DxIjCh5UZXh0Q2hlY2tGcmllbmRHcm91cE5hbWVDcmVhdGUQ0w8SIwoeVGV4",
            "dENoZWNrRnJpZW5kR3JvdXBOYW1lQ2hhbmdlENQPEiAKG1RleHRDaGVja1Rl",
            "YW1UYXJnZXRRdWlja1NheRDVDxIaChVUZXh0Q2hlY2tTZWFyY2hGcmllbmQQ",
            "oR8SHwoaVGV4dENoZWNrU2VhcmNoVW5pb25NZW1iZXIQoh8SGQoUVGV4dENo",
            "ZWNrU2VhcmNoVW5pb24Qox8SJQogVGV4dENoZWNrSG9tZWxhbmRPdXRlclN0",
            "cnVjdHVyZXMQ0SgSJQogVGV4dENoZWNrSG9tZWxhbmRJbm5lclN0cnVjdHVy",
            "ZXMQ0ihiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zproto.TextCheckSceneType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum TextCheckSceneType {
    [pbr::OriginalName("TextCheckError")] TextCheckError = 0,
    [pbr::OriginalName("TextCheckCreateRoleName")] TextCheckCreateRoleName = 101,
    [pbr::OriginalName("TextCheckCreateUnionName")] TextCheckCreateUnionName = 102,
    [pbr::OriginalName("TextCheckUnionManifesto")] TextCheckUnionManifesto = 103,
    [pbr::OriginalName("TextCheckUnionJobName")] TextCheckUnionJobName = 104,
    [pbr::OriginalName("TextCheckUnionRecruit")] TextCheckUnionRecruit = 105,
    [pbr::OriginalName("TextCheckUnionRecruitDescription")] TextCheckUnionRecruitDescription = 106,
    [pbr::OriginalName("TextCheckMapCustomFlag")] TextCheckMapCustomFlag = 108,
    [pbr::OriginalName("TextCheckAlbumName")] TextCheckAlbumName = 109,
    [pbr::OriginalName("TextCheckChangeName")] TextCheckChangeName = 110,
    [pbr::OriginalName("TextCheckUnionChangeName")] TextCheckUnionChangeName = 111,
    [pbr::OriginalName("TextCheckAlbumUploadTmp")] TextCheckAlbumUploadTmp = 112,
    [pbr::OriginalName("TextCheckAlbumPhotoEditText")] TextCheckAlbumPhotoEditText = 113,
    [pbr::OriginalName("TextCheckAlbumPhotoEditUpload")] TextCheckAlbumPhotoEditUpload = 114,
    [pbr::OriginalName("TextCheckAlbumUploadPhoto")] TextCheckAlbumUploadPhoto = 115,
    [pbr::OriginalName("TextCheckUnionUploadHead")] TextCheckUnionUploadHead = 116,
    [pbr::OriginalName("TextCheckUnionUploadCard")] TextCheckUnionUploadCard = 117,
    [pbr::OriginalName("TextCheckAlbumChangeName")] TextCheckAlbumChangeName = 118,
    [pbr::OriginalName("TextCheckCommunityCheckIntroduce")] TextCheckCommunityCheckIntroduce = 119,
    [pbr::OriginalName("TextCheckCommunityCheckInvite")] TextCheckCommunityCheckInvite = 120,
    [pbr::OriginalName("TextCheckCommunityCheckLightingName")] TextCheckCommunityCheckLightingName = 121,
    [pbr::OriginalName("TextCheckCommunityCheckCombinationFurnitureName")] TextCheckCommunityCheckCombinationFurnitureName = 122,
    [pbr::OriginalName("TextCheckCommunityCheckPhotoName")] TextCheckCommunityCheckPhotoName = 123,
    [pbr::OriginalName("TextCheckCommunityCheckName")] TextCheckCommunityCheckName = 124,
    [pbr::OriginalName("TextCheckUnionAlbumName")] TextCheckUnionAlbumName = 125,
    [pbr::OriginalName("TextCheckChangeUnionAlbumName")] TextCheckChangeUnionAlbumName = 126,
    [pbr::OriginalName("TextCheckChangeMapCustomFlag")] TextCheckChangeMapCustomFlag = 127,
    [pbr::OriginalName("TextCheckChangeUnionRecruit")] TextCheckChangeUnionRecruit = 128,
    [pbr::OriginalName("TextCheckChangeUnionRecruitDescription")] TextCheckChangeUnionRecruitDescription = 129,
    [pbr::OriginalName("TextCheckUnionAlbumUploadPhoto")] TextCheckUnionAlbumUploadPhoto = 130,
    [pbr::OriginalName("TextCheckChatWorldChannel")] TextCheckChatWorldChannel = 1001,
    [pbr::OriginalName("TextCheckChatUnionChannel")] TextCheckChatUnionChannel = 1002,
    [pbr::OriginalName("TextCheckChatTeamChannel")] TextCheckChatTeamChannel = 1003,
    [pbr::OriginalName("TextCheckChatPrivateChannel")] TextCheckChatPrivateChannel = 1005,
    [pbr::OriginalName("TextCheckChatSceneChannel")] TextCheckChatSceneChannel = 1006,
    [pbr::OriginalName("TextCheckFriendRemark")] TextCheckFriendRemark = 2001,
    [pbr::OriginalName("TextCheckTeamTargetInfo")] TextCheckTeamTargetInfo = 2002,
    [pbr::OriginalName("TextCheckFriendGroupNameCreate")] TextCheckFriendGroupNameCreate = 2003,
    [pbr::OriginalName("TextCheckFriendGroupNameChange")] TextCheckFriendGroupNameChange = 2004,
    [pbr::OriginalName("TextCheckTeamTargetQuickSay")] TextCheckTeamTargetQuickSay = 2005,
    [pbr::OriginalName("TextCheckSearchFriend")] TextCheckSearchFriend = 4001,
    [pbr::OriginalName("TextCheckSearchUnionMember")] TextCheckSearchUnionMember = 4002,
    [pbr::OriginalName("TextCheckSearchUnion")] TextCheckSearchUnion = 4003,
    [pbr::OriginalName("TextCheckHomelandOuterStructures")] TextCheckHomelandOuterStructures = 5201,
    [pbr::OriginalName("TextCheckHomelandInnerStructures")] TextCheckHomelandInnerStructures = 5202,
  }

  #endregion

}

#endregion Designer generated code
