// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_home_land_sell_shop_info.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_home_land_sell_shop_info.proto</summary>
  public static partial class StruHomeLandSellShopInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_home_land_sell_shop_info.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruHomeLandSellShopInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNzdHJ1X2hvbWVfbGFuZF9zZWxsX3Nob3BfaW5mby5wcm90bxIGenByb3Rv",
            "GhpzdHJ1X2NvbGxlY3RpbmdfaXRlbS5wcm90byLfAQoUSG9tZUxhbmRTZWxs",
            "U2hvcEluZm8SDwoHaXNfaW5pdBgBIAEoCBIZChFuZXh0X3JlZmx1c2hfdGlt",
            "ZRgCIAEoAxJLChBjb2xsZWN0aW5nX2l0ZW1zGAMgAygLMjEuenByb3RvLkhv",
            "bWVMYW5kU2VsbFNob3BJbmZvLkNvbGxlY3RpbmdJdGVtc0VudHJ5Gk4KFENv",
            "bGxlY3RpbmdJdGVtc0VudHJ5EgsKA2tleRgBIAEoBRIlCgV2YWx1ZRgCIAEo",
            "CzIWLnpwcm90by5Db2xsZWN0aW5nSXRlbToCOAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruCollectingItemReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.HomeLandSellShopInfo), global::Zproto.HomeLandSellShopInfo.Parser, new[]{ "IsInit", "NextReflushTime", "CollectingItems" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class HomeLandSellShopInfo : pb::IMessage<HomeLandSellShopInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HomeLandSellShopInfo> _parser = new pb::MessageParser<HomeLandSellShopInfo>(() => new HomeLandSellShopInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HomeLandSellShopInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruHomeLandSellShopInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HomeLandSellShopInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HomeLandSellShopInfo(HomeLandSellShopInfo other) : this() {
      isInit_ = other.isInit_;
      nextReflushTime_ = other.nextReflushTime_;
      collectingItems_ = other.collectingItems_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HomeLandSellShopInfo Clone() {
      return new HomeLandSellShopInfo(this);
    }

    /// <summary>Field number for the "is_init" field.</summary>
    public const int IsInitFieldNumber = 1;
    private bool isInit_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsInit {
      get { return isInit_; }
      set {
        isInit_ = value;
      }
    }

    /// <summary>Field number for the "next_reflush_time" field.</summary>
    public const int NextReflushTimeFieldNumber = 2;
    private long nextReflushTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long NextReflushTime {
      get { return nextReflushTime_; }
      set {
        nextReflushTime_ = value;
      }
    }

    /// <summary>Field number for the "collecting_items" field.</summary>
    public const int CollectingItemsFieldNumber = 3;
    private static readonly pbc::MapField<int, global::Zproto.CollectingItem>.Codec _map_collectingItems_codec
        = new pbc::MapField<int, global::Zproto.CollectingItem>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Zproto.CollectingItem.Parser), 26);
    private readonly pbc::MapField<int, global::Zproto.CollectingItem> collectingItems_ = new pbc::MapField<int, global::Zproto.CollectingItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::Zproto.CollectingItem> CollectingItems {
      get { return collectingItems_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HomeLandSellShopInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HomeLandSellShopInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IsInit != other.IsInit) return false;
      if (NextReflushTime != other.NextReflushTime) return false;
      if (!CollectingItems.Equals(other.CollectingItems)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IsInit != false) hash ^= IsInit.GetHashCode();
      if (NextReflushTime != 0L) hash ^= NextReflushTime.GetHashCode();
      hash ^= CollectingItems.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IsInit != false) {
        output.WriteRawTag(8);
        output.WriteBool(IsInit);
      }
      if (NextReflushTime != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(NextReflushTime);
      }
      collectingItems_.WriteTo(output, _map_collectingItems_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IsInit != false) {
        output.WriteRawTag(8);
        output.WriteBool(IsInit);
      }
      if (NextReflushTime != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(NextReflushTime);
      }
      collectingItems_.WriteTo(ref output, _map_collectingItems_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IsInit != false) {
        size += 1 + 1;
      }
      if (NextReflushTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(NextReflushTime);
      }
      size += collectingItems_.CalculateSize(_map_collectingItems_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HomeLandSellShopInfo other) {
      if (other == null) {
        return;
      }
      if (other.IsInit != false) {
        IsInit = other.IsInit;
      }
      if (other.NextReflushTime != 0L) {
        NextReflushTime = other.NextReflushTime;
      }
      collectingItems_.MergeFrom(other.collectingItems_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IsInit = input.ReadBool();
            break;
          }
          case 16: {
            NextReflushTime = input.ReadInt64();
            break;
          }
          case 26: {
            collectingItems_.AddEntriesFrom(input, _map_collectingItems_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            IsInit = input.ReadBool();
            break;
          }
          case 16: {
            NextReflushTime = input.ReadInt64();
            break;
          }
          case 26: {
            collectingItems_.AddEntriesFrom(ref input, _map_collectingItems_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
