// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_community_get_home_land_base_info_reply.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_community_get_home_land_base_info_reply.proto</summary>
  public static partial class StruCommunityGetHomeLandBaseInfoReplyReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_community_get_home_land_base_info_reply.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruCommunityGetHomeLandBaseInfoReplyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjJzdHJ1X2NvbW11bml0eV9nZXRfaG9tZV9sYW5kX2Jhc2VfaW5mb19yZXBs",
            "eS5wcm90bxIGenByb3RvGhdlbnVtX2VfZXJyb3JfY29kZS5wcm90bxodc3Ry",
            "dV9ob21lbGFuZF9iYXNlX2luZm8ucHJvdG8ifwohQ29tbXVuaXR5R2V0SG9t",
            "ZUxhbmRCYXNlSW5mb1JlcGx5EjQKEmhvbWVsYW5kX2Jhc2VfaW5mbxgBIAEo",
            "CzIYLnpwcm90by5Ib21lbGFuZEJhc2VJbmZvEiQKCGVycl9jb2RlGAIgASgO",
            "MhIuenByb3RvLkVFcnJvckNvZGViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.EnumEErrorCodeReflection.Descriptor, global::Zproto.StruHomelandBaseInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.CommunityGetHomeLandBaseInfoReply), global::Zproto.CommunityGetHomeLandBaseInfoReply.Parser, new[]{ "HomelandBaseInfo", "ErrCode" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CommunityGetHomeLandBaseInfoReply : pb::IMessage<CommunityGetHomeLandBaseInfoReply>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CommunityGetHomeLandBaseInfoReply> _parser = new pb::MessageParser<CommunityGetHomeLandBaseInfoReply>(() => new CommunityGetHomeLandBaseInfoReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CommunityGetHomeLandBaseInfoReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruCommunityGetHomeLandBaseInfoReplyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CommunityGetHomeLandBaseInfoReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CommunityGetHomeLandBaseInfoReply(CommunityGetHomeLandBaseInfoReply other) : this() {
      homelandBaseInfo_ = other.homelandBaseInfo_ != null ? other.homelandBaseInfo_.Clone() : null;
      errCode_ = other.errCode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CommunityGetHomeLandBaseInfoReply Clone() {
      return new CommunityGetHomeLandBaseInfoReply(this);
    }

    /// <summary>Field number for the "homeland_base_info" field.</summary>
    public const int HomelandBaseInfoFieldNumber = 1;
    private global::Zproto.HomelandBaseInfo homelandBaseInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.HomelandBaseInfo HomelandBaseInfo {
      get { return homelandBaseInfo_; }
      set {
        homelandBaseInfo_ = value;
      }
    }

    /// <summary>Field number for the "err_code" field.</summary>
    public const int ErrCodeFieldNumber = 2;
    private global::Zproto.EErrorCode errCode_ = global::Zproto.EErrorCode.ErrSuccess;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.EErrorCode ErrCode {
      get { return errCode_; }
      set {
        errCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CommunityGetHomeLandBaseInfoReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CommunityGetHomeLandBaseInfoReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(HomelandBaseInfo, other.HomelandBaseInfo)) return false;
      if (ErrCode != other.ErrCode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (homelandBaseInfo_ != null) hash ^= HomelandBaseInfo.GetHashCode();
      if (ErrCode != global::Zproto.EErrorCode.ErrSuccess) hash ^= ErrCode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (homelandBaseInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(HomelandBaseInfo);
      }
      if (ErrCode != global::Zproto.EErrorCode.ErrSuccess) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ErrCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (homelandBaseInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(HomelandBaseInfo);
      }
      if (ErrCode != global::Zproto.EErrorCode.ErrSuccess) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ErrCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (homelandBaseInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HomelandBaseInfo);
      }
      if (ErrCode != global::Zproto.EErrorCode.ErrSuccess) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ErrCode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CommunityGetHomeLandBaseInfoReply other) {
      if (other == null) {
        return;
      }
      if (other.homelandBaseInfo_ != null) {
        if (homelandBaseInfo_ == null) {
          HomelandBaseInfo = new global::Zproto.HomelandBaseInfo();
        }
        HomelandBaseInfo.MergeFrom(other.HomelandBaseInfo);
      }
      if (other.ErrCode != global::Zproto.EErrorCode.ErrSuccess) {
        ErrCode = other.ErrCode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (homelandBaseInfo_ == null) {
              HomelandBaseInfo = new global::Zproto.HomelandBaseInfo();
            }
            input.ReadMessage(HomelandBaseInfo);
            break;
          }
          case 16: {
            ErrCode = (global::Zproto.EErrorCode) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (homelandBaseInfo_ == null) {
              HomelandBaseInfo = new global::Zproto.HomelandBaseInfo();
            }
            input.ReadMessage(HomelandBaseInfo);
            break;
          }
          case 16: {
            ErrCode = (global::Zproto.EErrorCode) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
