// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_newbie_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_newbie_data.proto</summary>
  public static partial class StruNewbieDataReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_newbie_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruNewbieDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZzdHJ1X25ld2JpZV9kYXRhLnByb3RvEgZ6cHJvdG8aFXN0cnVfZGlydHlf",
            "bWFzay5wcm90byJUCgpOZXdiaWVEYXRhEhkKEXRvdGFsX29ubGluZV90aW1l",
            "GAEgASgDEhEKCWlzX25ld2JpZRgCIAEoCBIYChBpc19jYW5jZWxfbmV3Ymll",
            "GAMgASgIYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruDirtyMaskReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.NewbieData), global::Zproto.NewbieData.Parser, new[]{ "TotalOnlineTime", "IsNewbie", "IsCancelNewbie" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class NewbieData : pb::IMessage<NewbieData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NewbieData> _parser = new pb::MessageParser<NewbieData>(() => new NewbieData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NewbieData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruNewbieDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NewbieData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NewbieData(NewbieData other) : this() {
      totalOnlineTime_ = other.totalOnlineTime_;
      isNewbie_ = other.isNewbie_;
      isCancelNewbie_ = other.isCancelNewbie_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NewbieData Clone() {
      return new NewbieData(this);
    }

    /// <summary>Field number for the "total_online_time" field.</summary>
    public const int TotalOnlineTimeFieldNumber = 1;
    private long totalOnlineTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TotalOnlineTime {
      get { return totalOnlineTime_; }
      set {
        totalOnlineTime_ = value;
      }
    }

    /// <summary>Field number for the "is_newbie" field.</summary>
    public const int IsNewbieFieldNumber = 2;
    private bool isNewbie_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsNewbie {
      get { return isNewbie_; }
      set {
        isNewbie_ = value;
      }
    }

    /// <summary>Field number for the "is_cancel_newbie" field.</summary>
    public const int IsCancelNewbieFieldNumber = 3;
    private bool isCancelNewbie_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsCancelNewbie {
      get { return isCancelNewbie_; }
      set {
        isCancelNewbie_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NewbieData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NewbieData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TotalOnlineTime != other.TotalOnlineTime) return false;
      if (IsNewbie != other.IsNewbie) return false;
      if (IsCancelNewbie != other.IsCancelNewbie) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TotalOnlineTime != 0L) hash ^= TotalOnlineTime.GetHashCode();
      if (IsNewbie != false) hash ^= IsNewbie.GetHashCode();
      if (IsCancelNewbie != false) hash ^= IsCancelNewbie.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TotalOnlineTime != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(TotalOnlineTime);
      }
      if (IsNewbie != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsNewbie);
      }
      if (IsCancelNewbie != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsCancelNewbie);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TotalOnlineTime != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(TotalOnlineTime);
      }
      if (IsNewbie != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsNewbie);
      }
      if (IsCancelNewbie != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsCancelNewbie);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TotalOnlineTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TotalOnlineTime);
      }
      if (IsNewbie != false) {
        size += 1 + 1;
      }
      if (IsCancelNewbie != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NewbieData other) {
      if (other == null) {
        return;
      }
      if (other.TotalOnlineTime != 0L) {
        TotalOnlineTime = other.TotalOnlineTime;
      }
      if (other.IsNewbie != false) {
        IsNewbie = other.IsNewbie;
      }
      if (other.IsCancelNewbie != false) {
        IsCancelNewbie = other.IsCancelNewbie;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TotalOnlineTime = input.ReadInt64();
            break;
          }
          case 16: {
            IsNewbie = input.ReadBool();
            break;
          }
          case 24: {
            IsCancelNewbie = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TotalOnlineTime = input.ReadInt64();
            break;
          }
          case 16: {
            IsNewbie = input.ReadBool();
            break;
          }
          case 24: {
            IsCancelNewbie = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
