// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_profession_list.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_profession_list.proto</summary>
  public static partial class StruProfessionListReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_profession_list.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruProfessionListReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpzdHJ1X3Byb2Zlc3Npb25fbGlzdC5wcm90bxIGenByb3RvGhpzdHJ1X3By",
            "b2Zlc3Npb25faW5mby5wcm90bxogc3RydV9wcm9mZXNzaW9uX3NraWxsX2lu",
            "Zm8ucHJvdG8aIXN0cnVfcHJvZmVzc2lvbl90YWxlbnRfaW5mby5wcm90bxoV",
            "c3RydV9kaXJ0eV9tYXNrLnByb3RvIs0ECg5Qcm9mZXNzaW9uTGlzdBIZChFj",
            "dXJfcHJvZmVzc2lvbl9pZBgBIAEoBRIeChZjdXJfYXNzaXN0X3Byb2Zlc3Np",
            "b25zGAMgAygFEkMKD3Byb2Zlc3Npb25fbGlzdBgEIAMoCzIqLnpwcm90by5Q",
            "cm9mZXNzaW9uTGlzdC5Qcm9mZXNzaW9uTGlzdEVudHJ5EkkKE2FveWlfc2tp",
            "bGxfaW5mb19tYXAYByADKAsyLC56cHJvdG8uUHJvZmVzc2lvbkxpc3QuQW95",
            "aVNraWxsSW5mb01hcEVudHJ5EhsKE3RvdGFsX3RhbGVudF9wb2ludHMYCCAB",
            "KA0SIAoYdG90YWxfdGFsZW50X3Jlc2V0X2NvdW50GAkgASgNEjsKC3RhbGVu",
            "dF9saXN0GAogAygLMiYuenByb3RvLlByb2Zlc3Npb25MaXN0LlRhbGVudExp",
            "c3RFbnRyeRpNChNQcm9mZXNzaW9uTGlzdEVudHJ5EgsKA2tleRgBIAEoBRIl",
            "CgV2YWx1ZRgCIAEoCzIWLnpwcm90by5Qcm9mZXNzaW9uSW5mbzoCOAEaVAoV",
            "QW95aVNraWxsSW5mb01hcEVudHJ5EgsKA2tleRgBIAEoBRIqCgV2YWx1ZRgC",
            "IAEoCzIbLnpwcm90by5Qcm9mZXNzaW9uU2tpbGxJbmZvOgI4ARpPCg9UYWxl",
            "bnRMaXN0RW50cnkSCwoDa2V5GAEgASgFEisKBXZhbHVlGAIgASgLMhwuenBy",
            "b3RvLlByb2Zlc3Npb25UYWxlbnRJbmZvOgI4AWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruProfessionInfoReflection.Descriptor, global::Zproto.StruProfessionSkillInfoReflection.Descriptor, global::Zproto.StruProfessionTalentInfoReflection.Descriptor, global::Zproto.StruDirtyMaskReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.ProfessionList), global::Zproto.ProfessionList.Parser, new[]{ "CurProfessionId", "CurAssistProfessions", "ProfessionList_", "AoyiSkillInfoMap", "TotalTalentPoints", "TotalTalentResetCount", "TalentList" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ProfessionList : pb::IMessage<ProfessionList>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProfessionList> _parser = new pb::MessageParser<ProfessionList>(() => new ProfessionList());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProfessionList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruProfessionListReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProfessionList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProfessionList(ProfessionList other) : this() {
      curProfessionId_ = other.curProfessionId_;
      curAssistProfessions_ = other.curAssistProfessions_.Clone();
      professionList_ = other.professionList_.Clone();
      aoyiSkillInfoMap_ = other.aoyiSkillInfoMap_.Clone();
      totalTalentPoints_ = other.totalTalentPoints_;
      totalTalentResetCount_ = other.totalTalentResetCount_;
      talentList_ = other.talentList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProfessionList Clone() {
      return new ProfessionList(this);
    }

    /// <summary>Field number for the "cur_profession_id" field.</summary>
    public const int CurProfessionIdFieldNumber = 1;
    private int curProfessionId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CurProfessionId {
      get { return curProfessionId_; }
      set {
        curProfessionId_ = value;
      }
    }

    /// <summary>Field number for the "cur_assist_professions" field.</summary>
    public const int CurAssistProfessionsFieldNumber = 3;
    private static readonly pb::FieldCodec<int> _repeated_curAssistProfessions_codec
        = pb::FieldCodec.ForInt32(26);
    private readonly pbc::RepeatedField<int> curAssistProfessions_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> CurAssistProfessions {
      get { return curAssistProfessions_; }
    }

    /// <summary>Field number for the "profession_list" field.</summary>
    public const int ProfessionList_FieldNumber = 4;
    private static readonly pbc::MapField<int, global::Zproto.ProfessionInfo>.Codec _map_professionList_codec
        = new pbc::MapField<int, global::Zproto.ProfessionInfo>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Zproto.ProfessionInfo.Parser), 34);
    private readonly pbc::MapField<int, global::Zproto.ProfessionInfo> professionList_ = new pbc::MapField<int, global::Zproto.ProfessionInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::Zproto.ProfessionInfo> ProfessionList_ {
      get { return professionList_; }
    }

    /// <summary>Field number for the "aoyi_skill_info_map" field.</summary>
    public const int AoyiSkillInfoMapFieldNumber = 7;
    private static readonly pbc::MapField<int, global::Zproto.ProfessionSkillInfo>.Codec _map_aoyiSkillInfoMap_codec
        = new pbc::MapField<int, global::Zproto.ProfessionSkillInfo>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Zproto.ProfessionSkillInfo.Parser), 58);
    private readonly pbc::MapField<int, global::Zproto.ProfessionSkillInfo> aoyiSkillInfoMap_ = new pbc::MapField<int, global::Zproto.ProfessionSkillInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::Zproto.ProfessionSkillInfo> AoyiSkillInfoMap {
      get { return aoyiSkillInfoMap_; }
    }

    /// <summary>Field number for the "total_talent_points" field.</summary>
    public const int TotalTalentPointsFieldNumber = 8;
    private uint totalTalentPoints_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TotalTalentPoints {
      get { return totalTalentPoints_; }
      set {
        totalTalentPoints_ = value;
      }
    }

    /// <summary>Field number for the "total_talent_reset_count" field.</summary>
    public const int TotalTalentResetCountFieldNumber = 9;
    private uint totalTalentResetCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TotalTalentResetCount {
      get { return totalTalentResetCount_; }
      set {
        totalTalentResetCount_ = value;
      }
    }

    /// <summary>Field number for the "talent_list" field.</summary>
    public const int TalentListFieldNumber = 10;
    private static readonly pbc::MapField<int, global::Zproto.ProfessionTalentInfo>.Codec _map_talentList_codec
        = new pbc::MapField<int, global::Zproto.ProfessionTalentInfo>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Zproto.ProfessionTalentInfo.Parser), 82);
    private readonly pbc::MapField<int, global::Zproto.ProfessionTalentInfo> talentList_ = new pbc::MapField<int, global::Zproto.ProfessionTalentInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::Zproto.ProfessionTalentInfo> TalentList {
      get { return talentList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProfessionList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProfessionList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CurProfessionId != other.CurProfessionId) return false;
      if(!curAssistProfessions_.Equals(other.curAssistProfessions_)) return false;
      if (!ProfessionList_.Equals(other.ProfessionList_)) return false;
      if (!AoyiSkillInfoMap.Equals(other.AoyiSkillInfoMap)) return false;
      if (TotalTalentPoints != other.TotalTalentPoints) return false;
      if (TotalTalentResetCount != other.TotalTalentResetCount) return false;
      if (!TalentList.Equals(other.TalentList)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CurProfessionId != 0) hash ^= CurProfessionId.GetHashCode();
      hash ^= curAssistProfessions_.GetHashCode();
      hash ^= ProfessionList_.GetHashCode();
      hash ^= AoyiSkillInfoMap.GetHashCode();
      if (TotalTalentPoints != 0) hash ^= TotalTalentPoints.GetHashCode();
      if (TotalTalentResetCount != 0) hash ^= TotalTalentResetCount.GetHashCode();
      hash ^= TalentList.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CurProfessionId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(CurProfessionId);
      }
      curAssistProfessions_.WriteTo(output, _repeated_curAssistProfessions_codec);
      professionList_.WriteTo(output, _map_professionList_codec);
      aoyiSkillInfoMap_.WriteTo(output, _map_aoyiSkillInfoMap_codec);
      if (TotalTalentPoints != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(TotalTalentPoints);
      }
      if (TotalTalentResetCount != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(TotalTalentResetCount);
      }
      talentList_.WriteTo(output, _map_talentList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CurProfessionId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(CurProfessionId);
      }
      curAssistProfessions_.WriteTo(ref output, _repeated_curAssistProfessions_codec);
      professionList_.WriteTo(ref output, _map_professionList_codec);
      aoyiSkillInfoMap_.WriteTo(ref output, _map_aoyiSkillInfoMap_codec);
      if (TotalTalentPoints != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(TotalTalentPoints);
      }
      if (TotalTalentResetCount != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(TotalTalentResetCount);
      }
      talentList_.WriteTo(ref output, _map_talentList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CurProfessionId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CurProfessionId);
      }
      size += curAssistProfessions_.CalculateSize(_repeated_curAssistProfessions_codec);
      size += professionList_.CalculateSize(_map_professionList_codec);
      size += aoyiSkillInfoMap_.CalculateSize(_map_aoyiSkillInfoMap_codec);
      if (TotalTalentPoints != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TotalTalentPoints);
      }
      if (TotalTalentResetCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TotalTalentResetCount);
      }
      size += talentList_.CalculateSize(_map_talentList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProfessionList other) {
      if (other == null) {
        return;
      }
      if (other.CurProfessionId != 0) {
        CurProfessionId = other.CurProfessionId;
      }
      curAssistProfessions_.Add(other.curAssistProfessions_);
      professionList_.MergeFrom(other.professionList_);
      aoyiSkillInfoMap_.MergeFrom(other.aoyiSkillInfoMap_);
      if (other.TotalTalentPoints != 0) {
        TotalTalentPoints = other.TotalTalentPoints;
      }
      if (other.TotalTalentResetCount != 0) {
        TotalTalentResetCount = other.TotalTalentResetCount;
      }
      talentList_.MergeFrom(other.talentList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            CurProfessionId = input.ReadInt32();
            break;
          }
          case 26:
          case 24: {
            curAssistProfessions_.AddEntriesFrom(input, _repeated_curAssistProfessions_codec);
            break;
          }
          case 34: {
            professionList_.AddEntriesFrom(input, _map_professionList_codec);
            break;
          }
          case 58: {
            aoyiSkillInfoMap_.AddEntriesFrom(input, _map_aoyiSkillInfoMap_codec);
            break;
          }
          case 64: {
            TotalTalentPoints = input.ReadUInt32();
            break;
          }
          case 72: {
            TotalTalentResetCount = input.ReadUInt32();
            break;
          }
          case 82: {
            talentList_.AddEntriesFrom(input, _map_talentList_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            CurProfessionId = input.ReadInt32();
            break;
          }
          case 26:
          case 24: {
            curAssistProfessions_.AddEntriesFrom(ref input, _repeated_curAssistProfessions_codec);
            break;
          }
          case 34: {
            professionList_.AddEntriesFrom(ref input, _map_professionList_codec);
            break;
          }
          case 58: {
            aoyiSkillInfoMap_.AddEntriesFrom(ref input, _map_aoyiSkillInfoMap_codec);
            break;
          }
          case 64: {
            TotalTalentPoints = input.ReadUInt32();
            break;
          }
          case 72: {
            TotalTalentResetCount = input.ReadUInt32();
            break;
          }
          case 82: {
            talentList_.AddEntriesFrom(ref input, _map_talentList_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
