// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_dungeon_sync_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_dungeon_sync_data.proto</summary>
  public static partial class StruDungeonSyncDataReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_dungeon_sync_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruDungeonSyncDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxzdHJ1X2R1bmdlb25fc3luY19kYXRhLnByb3RvEgZ6cHJvdG8aHXN0cnVf",
            "ZHVuZ2Vvbl9hZmZpeF9kYXRhLnByb3RvGhlzdHJ1X2R1bmdlb25fZGFtYWdl",
            "LnByb3RvGhhzdHJ1X2R1bmdlb25fZXZlbnQucHJvdG8aHHN0cnVfZHVuZ2Vv",
            "bl9mbG93X2luZm8ucHJvdG8aIHN0cnVfZHVuZ2Vvbl9oZXJvX2tleV9pbmZv",
            "LnByb3RvGhpzdHJ1X2R1bmdlb25fcGlvbmVlci5wcm90bxolc3RydV9kdW5n",
            "ZW9uX3BsYW5ldF9tZW1vcnlfcm9vbS5wcm90bxoec3RydV9kdW5nZW9uX3Bs",
            "YXllcl9saXN0LnByb3RvGhxzdHJ1X2R1bmdlb25fcmFpZF9pbmZvLnByb3Rv",
            "Gi9zdHJ1X2R1bmdlb25fcmFuZG9tX2VudGl0eV9jb25maWdfaWRfaW5mby5w",
            "cm90bxocc3RydV9kdW5nZW9uX3JhbmtfbGlzdC5wcm90bxoec3RydV9kdW5n",
            "ZW9uX3Jldml2ZV9pbmZvLnByb3RvGh1zdHJ1X2R1bmdlb25fc2NlbmVfaW5m",
            "by5wcm90bxoYc3RydV9kdW5nZW9uX3Njb3JlLnByb3RvGh1zdHJ1X2R1bmdl",
            "b25fc2V0dGxlbWVudC5wcm90bxoZc3RydV9kdW5nZW9uX3RhcmdldC5wcm90",
            "bxodc3RydV9kdW5nZW9uX3RpbWVyX2luZm8ucHJvdG8aGHN0cnVfZHVuZ2Vv",
            "bl90aXRsZS5wcm90bxodc3RydV9kdW5nZW9uX3VuaW9uX2luZm8ucHJvdG8a",
            "FnN0cnVfZHVuZ2Vvbl92YXIucHJvdG8aGnN0cnVfZHVuZ2Vvbl92YXJfYWxs",
            "LnByb3RvGhdzdHJ1X2R1bmdlb25fdm90ZS5wcm90bxoXZW51bV9lX2Vycm9y",
            "X2NvZGUucHJvdG8aFXN0cnVfZGlydHlfbWFzay5wcm90byLzCAoPRHVuZ2Vv",
            "blN5bmNEYXRhEhIKCnNjZW5lX3V1aWQYASABKAMSKgoJZmxvd19pbmZvGAIg",
            "ASgLMhcuenByb3RvLkR1bmdlb25GbG93SW5mbxIjCgV0aXRsZRgDIAEoCzIU",
            "Lnpwcm90by5EdW5nZW9uVGl0bGUSJQoGdGFyZ2V0GAQgASgLMhUuenByb3Rv",
            "LkR1bmdlb25UYXJnZXQSJQoGZGFtYWdlGAUgASgLMhUuenByb3RvLkR1bmdl",
            "b25EYW1hZ2USIQoEdm90ZRgGIAEoCzITLnpwcm90by5EdW5nZW9uVm90ZRIt",
            "CgpzZXR0bGVtZW50GAcgASgLMhkuenByb3RvLkR1bmdlb25TZXR0bGVtZW50",
            "Ei8KD2R1bmdlb25fcGlvbmVlchgIIAEoCzIWLnpwcm90by5EdW5nZW9uUGlv",
            "bmVlchI5ChBwbGFuZXRfcm9vbV9pbmZvGAkgASgLMh8uenByb3RvLkR1bmdl",
            "b25QbGFuZXRNZW1vcnlSb29tEicKC2R1bmdlb25fdmFyGAogASgLMhIuenBy",
            "b3RvLkR1bmdlb25WYXISLQoMZHVuZ2Vvbl9yYW5rGAsgASgLMhcuenByb3Rv",
            "LkR1bmdlb25SYW5rTGlzdBI0ChJkdW5nZW9uX2FmZml4X2RhdGEYDCABKAsy",
            "GC56cHJvdG8uRHVuZ2VvbkFmZml4RGF0YRIrCg1kdW5nZW9uX2V2ZW50GA0g",
            "ASgLMhQuenByb3RvLkR1bmdlb25FdmVudBIrCg1kdW5nZW9uX3Njb3JlGA4g",
            "ASgLMhQuenByb3RvLkR1bmdlb25TY29yZRIsCgp0aW1lcl9pbmZvGA8gASgL",
            "MhguenByb3RvLkR1bmdlb25UaW1lckluZm8SLAoIaGVyb19rZXkYECABKAsy",
            "Gi56cHJvdG8uRHVuZ2Vvbkhlcm9LZXlJbmZvEjQKEmR1bmdlb25fdW5pb25f",
            "aW5mbxgRIAEoCzIYLnpwcm90by5EdW5nZW9uVW5pb25JbmZvEjYKE2R1bmdl",
            "b25fcGxheWVyX2xpc3QYEiABKAsyGS56cHJvdG8uRHVuZ2VvblBsYXllckxp",
            "c3QSLgoLcmV2aXZlX2luZm8YEyABKAsyGS56cHJvdG8uRHVuZ2VvblJldml2",
            "ZUluZm8STQoccmFuZG9tX2VudGl0eV9jb25maWdfaWRfaW5mbxgUIAEoCzIn",
            "Lnpwcm90by5EdW5nZW9uUmFuZG9tRW50aXR5Q29uZmlnSWRJbmZvEjQKEmR1",
            "bmdlb25fc2NlbmVfaW5mbxgVIAEoCzIYLnpwcm90by5EdW5nZW9uU2NlbmVJ",
            "bmZvEi4KD2R1bmdlb25fdmFyX2FsbBgWIAEoCzIVLnpwcm90by5EdW5nZW9u",
            "VmFyQWxsEjIKEWR1bmdlb25fcmFpZF9pbmZvGBcgASgLMhcuenByb3RvLkR1",
            "bmdlb25SYWlkSW5mbxIkCghlcnJfY29kZRgYIAEoDjISLnpwcm90by5FRXJy",
            "b3JDb2RlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruDungeonAffixDataReflection.Descriptor, global::Zproto.StruDungeonDamageReflection.Descriptor, global::Zproto.StruDungeonEventReflection.Descriptor, global::Zproto.StruDungeonFlowInfoReflection.Descriptor, global::Zproto.StruDungeonHeroKeyInfoReflection.Descriptor, global::Zproto.StruDungeonPioneerReflection.Descriptor, global::Zproto.StruDungeonPlanetMemoryRoomReflection.Descriptor, global::Zproto.StruDungeonPlayerListReflection.Descriptor, global::Zproto.StruDungeonRaidInfoReflection.Descriptor, global::Zproto.StruDungeonRandomEntityConfigIdInfoReflection.Descriptor, global::Zproto.StruDungeonRankListReflection.Descriptor, global::Zproto.StruDungeonReviveInfoReflection.Descriptor, global::Zproto.StruDungeonSceneInfoReflection.Descriptor, global::Zproto.StruDungeonScoreReflection.Descriptor, global::Zproto.StruDungeonSettlementReflection.Descriptor, global::Zproto.StruDungeonTargetReflection.Descriptor, global::Zproto.StruDungeonTimerInfoReflection.Descriptor, global::Zproto.StruDungeonTitleReflection.Descriptor, global::Zproto.StruDungeonUnionInfoReflection.Descriptor, global::Zproto.StruDungeonVarReflection.Descriptor, global::Zproto.StruDungeonVarAllReflection.Descriptor, global::Zproto.StruDungeonVoteReflection.Descriptor, global::Zproto.EnumEErrorCodeReflection.Descriptor, global::Zproto.StruDirtyMaskReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.DungeonSyncData), global::Zproto.DungeonSyncData.Parser, new[]{ "SceneUuid", "FlowInfo", "Title", "Target", "Damage", "Vote", "Settlement", "DungeonPioneer", "PlanetRoomInfo", "DungeonVar", "DungeonRank", "DungeonAffixData", "DungeonEvent", "DungeonScore", "TimerInfo", "HeroKey", "DungeonUnionInfo", "DungeonPlayerList", "ReviveInfo", "RandomEntityConfigIdInfo", "DungeonSceneInfo", "DungeonVarAll", "DungeonRaidInfo", "ErrCode" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DungeonSyncData : pb::IMessage<DungeonSyncData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DungeonSyncData> _parser = new pb::MessageParser<DungeonSyncData>(() => new DungeonSyncData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DungeonSyncData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruDungeonSyncDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DungeonSyncData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DungeonSyncData(DungeonSyncData other) : this() {
      sceneUuid_ = other.sceneUuid_;
      flowInfo_ = other.flowInfo_ != null ? other.flowInfo_.Clone() : null;
      title_ = other.title_ != null ? other.title_.Clone() : null;
      target_ = other.target_ != null ? other.target_.Clone() : null;
      damage_ = other.damage_ != null ? other.damage_.Clone() : null;
      vote_ = other.vote_ != null ? other.vote_.Clone() : null;
      settlement_ = other.settlement_ != null ? other.settlement_.Clone() : null;
      dungeonPioneer_ = other.dungeonPioneer_ != null ? other.dungeonPioneer_.Clone() : null;
      planetRoomInfo_ = other.planetRoomInfo_ != null ? other.planetRoomInfo_.Clone() : null;
      dungeonVar_ = other.dungeonVar_ != null ? other.dungeonVar_.Clone() : null;
      dungeonRank_ = other.dungeonRank_ != null ? other.dungeonRank_.Clone() : null;
      dungeonAffixData_ = other.dungeonAffixData_ != null ? other.dungeonAffixData_.Clone() : null;
      dungeonEvent_ = other.dungeonEvent_ != null ? other.dungeonEvent_.Clone() : null;
      dungeonScore_ = other.dungeonScore_ != null ? other.dungeonScore_.Clone() : null;
      timerInfo_ = other.timerInfo_ != null ? other.timerInfo_.Clone() : null;
      heroKey_ = other.heroKey_ != null ? other.heroKey_.Clone() : null;
      dungeonUnionInfo_ = other.dungeonUnionInfo_ != null ? other.dungeonUnionInfo_.Clone() : null;
      dungeonPlayerList_ = other.dungeonPlayerList_ != null ? other.dungeonPlayerList_.Clone() : null;
      reviveInfo_ = other.reviveInfo_ != null ? other.reviveInfo_.Clone() : null;
      randomEntityConfigIdInfo_ = other.randomEntityConfigIdInfo_ != null ? other.randomEntityConfigIdInfo_.Clone() : null;
      dungeonSceneInfo_ = other.dungeonSceneInfo_ != null ? other.dungeonSceneInfo_.Clone() : null;
      dungeonVarAll_ = other.dungeonVarAll_ != null ? other.dungeonVarAll_.Clone() : null;
      dungeonRaidInfo_ = other.dungeonRaidInfo_ != null ? other.dungeonRaidInfo_.Clone() : null;
      errCode_ = other.errCode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DungeonSyncData Clone() {
      return new DungeonSyncData(this);
    }

    /// <summary>Field number for the "scene_uuid" field.</summary>
    public const int SceneUuidFieldNumber = 1;
    private long sceneUuid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SceneUuid {
      get { return sceneUuid_; }
      set {
        sceneUuid_ = value;
      }
    }

    /// <summary>Field number for the "flow_info" field.</summary>
    public const int FlowInfoFieldNumber = 2;
    private global::Zproto.DungeonFlowInfo flowInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.DungeonFlowInfo FlowInfo {
      get { return flowInfo_; }
      set {
        flowInfo_ = value;
      }
    }

    /// <summary>Field number for the "title" field.</summary>
    public const int TitleFieldNumber = 3;
    private global::Zproto.DungeonTitle title_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.DungeonTitle Title {
      get { return title_; }
      set {
        title_ = value;
      }
    }

    /// <summary>Field number for the "target" field.</summary>
    public const int TargetFieldNumber = 4;
    private global::Zproto.DungeonTarget target_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.DungeonTarget Target {
      get { return target_; }
      set {
        target_ = value;
      }
    }

    /// <summary>Field number for the "damage" field.</summary>
    public const int DamageFieldNumber = 5;
    private global::Zproto.DungeonDamage damage_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.DungeonDamage Damage {
      get { return damage_; }
      set {
        damage_ = value;
      }
    }

    /// <summary>Field number for the "vote" field.</summary>
    public const int VoteFieldNumber = 6;
    private global::Zproto.DungeonVote vote_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.DungeonVote Vote {
      get { return vote_; }
      set {
        vote_ = value;
      }
    }

    /// <summary>Field number for the "settlement" field.</summary>
    public const int SettlementFieldNumber = 7;
    private global::Zproto.DungeonSettlement settlement_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.DungeonSettlement Settlement {
      get { return settlement_; }
      set {
        settlement_ = value;
      }
    }

    /// <summary>Field number for the "dungeon_pioneer" field.</summary>
    public const int DungeonPioneerFieldNumber = 8;
    private global::Zproto.DungeonPioneer dungeonPioneer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.DungeonPioneer DungeonPioneer {
      get { return dungeonPioneer_; }
      set {
        dungeonPioneer_ = value;
      }
    }

    /// <summary>Field number for the "planet_room_info" field.</summary>
    public const int PlanetRoomInfoFieldNumber = 9;
    private global::Zproto.DungeonPlanetMemoryRoom planetRoomInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.DungeonPlanetMemoryRoom PlanetRoomInfo {
      get { return planetRoomInfo_; }
      set {
        planetRoomInfo_ = value;
      }
    }

    /// <summary>Field number for the "dungeon_var" field.</summary>
    public const int DungeonVarFieldNumber = 10;
    private global::Zproto.DungeonVar dungeonVar_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.DungeonVar DungeonVar {
      get { return dungeonVar_; }
      set {
        dungeonVar_ = value;
      }
    }

    /// <summary>Field number for the "dungeon_rank" field.</summary>
    public const int DungeonRankFieldNumber = 11;
    private global::Zproto.DungeonRankList dungeonRank_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.DungeonRankList DungeonRank {
      get { return dungeonRank_; }
      set {
        dungeonRank_ = value;
      }
    }

    /// <summary>Field number for the "dungeon_affix_data" field.</summary>
    public const int DungeonAffixDataFieldNumber = 12;
    private global::Zproto.DungeonAffixData dungeonAffixData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.DungeonAffixData DungeonAffixData {
      get { return dungeonAffixData_; }
      set {
        dungeonAffixData_ = value;
      }
    }

    /// <summary>Field number for the "dungeon_event" field.</summary>
    public const int DungeonEventFieldNumber = 13;
    private global::Zproto.DungeonEvent dungeonEvent_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.DungeonEvent DungeonEvent {
      get { return dungeonEvent_; }
      set {
        dungeonEvent_ = value;
      }
    }

    /// <summary>Field number for the "dungeon_score" field.</summary>
    public const int DungeonScoreFieldNumber = 14;
    private global::Zproto.DungeonScore dungeonScore_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.DungeonScore DungeonScore {
      get { return dungeonScore_; }
      set {
        dungeonScore_ = value;
      }
    }

    /// <summary>Field number for the "timer_info" field.</summary>
    public const int TimerInfoFieldNumber = 15;
    private global::Zproto.DungeonTimerInfo timerInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.DungeonTimerInfo TimerInfo {
      get { return timerInfo_; }
      set {
        timerInfo_ = value;
      }
    }

    /// <summary>Field number for the "hero_key" field.</summary>
    public const int HeroKeyFieldNumber = 16;
    private global::Zproto.DungeonHeroKeyInfo heroKey_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.DungeonHeroKeyInfo HeroKey {
      get { return heroKey_; }
      set {
        heroKey_ = value;
      }
    }

    /// <summary>Field number for the "dungeon_union_info" field.</summary>
    public const int DungeonUnionInfoFieldNumber = 17;
    private global::Zproto.DungeonUnionInfo dungeonUnionInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.DungeonUnionInfo DungeonUnionInfo {
      get { return dungeonUnionInfo_; }
      set {
        dungeonUnionInfo_ = value;
      }
    }

    /// <summary>Field number for the "dungeon_player_list" field.</summary>
    public const int DungeonPlayerListFieldNumber = 18;
    private global::Zproto.DungeonPlayerList dungeonPlayerList_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.DungeonPlayerList DungeonPlayerList {
      get { return dungeonPlayerList_; }
      set {
        dungeonPlayerList_ = value;
      }
    }

    /// <summary>Field number for the "revive_info" field.</summary>
    public const int ReviveInfoFieldNumber = 19;
    private global::Zproto.DungeonReviveInfo reviveInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.DungeonReviveInfo ReviveInfo {
      get { return reviveInfo_; }
      set {
        reviveInfo_ = value;
      }
    }

    /// <summary>Field number for the "random_entity_config_id_info" field.</summary>
    public const int RandomEntityConfigIdInfoFieldNumber = 20;
    private global::Zproto.DungeonRandomEntityConfigIdInfo randomEntityConfigIdInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.DungeonRandomEntityConfigIdInfo RandomEntityConfigIdInfo {
      get { return randomEntityConfigIdInfo_; }
      set {
        randomEntityConfigIdInfo_ = value;
      }
    }

    /// <summary>Field number for the "dungeon_scene_info" field.</summary>
    public const int DungeonSceneInfoFieldNumber = 21;
    private global::Zproto.DungeonSceneInfo dungeonSceneInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.DungeonSceneInfo DungeonSceneInfo {
      get { return dungeonSceneInfo_; }
      set {
        dungeonSceneInfo_ = value;
      }
    }

    /// <summary>Field number for the "dungeon_var_all" field.</summary>
    public const int DungeonVarAllFieldNumber = 22;
    private global::Zproto.DungeonVarAll dungeonVarAll_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.DungeonVarAll DungeonVarAll {
      get { return dungeonVarAll_; }
      set {
        dungeonVarAll_ = value;
      }
    }

    /// <summary>Field number for the "dungeon_raid_info" field.</summary>
    public const int DungeonRaidInfoFieldNumber = 23;
    private global::Zproto.DungeonRaidInfo dungeonRaidInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.DungeonRaidInfo DungeonRaidInfo {
      get { return dungeonRaidInfo_; }
      set {
        dungeonRaidInfo_ = value;
      }
    }

    /// <summary>Field number for the "err_code" field.</summary>
    public const int ErrCodeFieldNumber = 24;
    private global::Zproto.EErrorCode errCode_ = global::Zproto.EErrorCode.ErrSuccess;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.EErrorCode ErrCode {
      get { return errCode_; }
      set {
        errCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DungeonSyncData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DungeonSyncData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SceneUuid != other.SceneUuid) return false;
      if (!object.Equals(FlowInfo, other.FlowInfo)) return false;
      if (!object.Equals(Title, other.Title)) return false;
      if (!object.Equals(Target, other.Target)) return false;
      if (!object.Equals(Damage, other.Damage)) return false;
      if (!object.Equals(Vote, other.Vote)) return false;
      if (!object.Equals(Settlement, other.Settlement)) return false;
      if (!object.Equals(DungeonPioneer, other.DungeonPioneer)) return false;
      if (!object.Equals(PlanetRoomInfo, other.PlanetRoomInfo)) return false;
      if (!object.Equals(DungeonVar, other.DungeonVar)) return false;
      if (!object.Equals(DungeonRank, other.DungeonRank)) return false;
      if (!object.Equals(DungeonAffixData, other.DungeonAffixData)) return false;
      if (!object.Equals(DungeonEvent, other.DungeonEvent)) return false;
      if (!object.Equals(DungeonScore, other.DungeonScore)) return false;
      if (!object.Equals(TimerInfo, other.TimerInfo)) return false;
      if (!object.Equals(HeroKey, other.HeroKey)) return false;
      if (!object.Equals(DungeonUnionInfo, other.DungeonUnionInfo)) return false;
      if (!object.Equals(DungeonPlayerList, other.DungeonPlayerList)) return false;
      if (!object.Equals(ReviveInfo, other.ReviveInfo)) return false;
      if (!object.Equals(RandomEntityConfigIdInfo, other.RandomEntityConfigIdInfo)) return false;
      if (!object.Equals(DungeonSceneInfo, other.DungeonSceneInfo)) return false;
      if (!object.Equals(DungeonVarAll, other.DungeonVarAll)) return false;
      if (!object.Equals(DungeonRaidInfo, other.DungeonRaidInfo)) return false;
      if (ErrCode != other.ErrCode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SceneUuid != 0L) hash ^= SceneUuid.GetHashCode();
      if (flowInfo_ != null) hash ^= FlowInfo.GetHashCode();
      if (title_ != null) hash ^= Title.GetHashCode();
      if (target_ != null) hash ^= Target.GetHashCode();
      if (damage_ != null) hash ^= Damage.GetHashCode();
      if (vote_ != null) hash ^= Vote.GetHashCode();
      if (settlement_ != null) hash ^= Settlement.GetHashCode();
      if (dungeonPioneer_ != null) hash ^= DungeonPioneer.GetHashCode();
      if (planetRoomInfo_ != null) hash ^= PlanetRoomInfo.GetHashCode();
      if (dungeonVar_ != null) hash ^= DungeonVar.GetHashCode();
      if (dungeonRank_ != null) hash ^= DungeonRank.GetHashCode();
      if (dungeonAffixData_ != null) hash ^= DungeonAffixData.GetHashCode();
      if (dungeonEvent_ != null) hash ^= DungeonEvent.GetHashCode();
      if (dungeonScore_ != null) hash ^= DungeonScore.GetHashCode();
      if (timerInfo_ != null) hash ^= TimerInfo.GetHashCode();
      if (heroKey_ != null) hash ^= HeroKey.GetHashCode();
      if (dungeonUnionInfo_ != null) hash ^= DungeonUnionInfo.GetHashCode();
      if (dungeonPlayerList_ != null) hash ^= DungeonPlayerList.GetHashCode();
      if (reviveInfo_ != null) hash ^= ReviveInfo.GetHashCode();
      if (randomEntityConfigIdInfo_ != null) hash ^= RandomEntityConfigIdInfo.GetHashCode();
      if (dungeonSceneInfo_ != null) hash ^= DungeonSceneInfo.GetHashCode();
      if (dungeonVarAll_ != null) hash ^= DungeonVarAll.GetHashCode();
      if (dungeonRaidInfo_ != null) hash ^= DungeonRaidInfo.GetHashCode();
      if (ErrCode != global::Zproto.EErrorCode.ErrSuccess) hash ^= ErrCode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SceneUuid != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(SceneUuid);
      }
      if (flowInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(FlowInfo);
      }
      if (title_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Title);
      }
      if (target_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Target);
      }
      if (damage_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Damage);
      }
      if (vote_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Vote);
      }
      if (settlement_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Settlement);
      }
      if (dungeonPioneer_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(DungeonPioneer);
      }
      if (planetRoomInfo_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(PlanetRoomInfo);
      }
      if (dungeonVar_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(DungeonVar);
      }
      if (dungeonRank_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(DungeonRank);
      }
      if (dungeonAffixData_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(DungeonAffixData);
      }
      if (dungeonEvent_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(DungeonEvent);
      }
      if (dungeonScore_ != null) {
        output.WriteRawTag(114);
        output.WriteMessage(DungeonScore);
      }
      if (timerInfo_ != null) {
        output.WriteRawTag(122);
        output.WriteMessage(TimerInfo);
      }
      if (heroKey_ != null) {
        output.WriteRawTag(130, 1);
        output.WriteMessage(HeroKey);
      }
      if (dungeonUnionInfo_ != null) {
        output.WriteRawTag(138, 1);
        output.WriteMessage(DungeonUnionInfo);
      }
      if (dungeonPlayerList_ != null) {
        output.WriteRawTag(146, 1);
        output.WriteMessage(DungeonPlayerList);
      }
      if (reviveInfo_ != null) {
        output.WriteRawTag(154, 1);
        output.WriteMessage(ReviveInfo);
      }
      if (randomEntityConfigIdInfo_ != null) {
        output.WriteRawTag(162, 1);
        output.WriteMessage(RandomEntityConfigIdInfo);
      }
      if (dungeonSceneInfo_ != null) {
        output.WriteRawTag(170, 1);
        output.WriteMessage(DungeonSceneInfo);
      }
      if (dungeonVarAll_ != null) {
        output.WriteRawTag(178, 1);
        output.WriteMessage(DungeonVarAll);
      }
      if (dungeonRaidInfo_ != null) {
        output.WriteRawTag(186, 1);
        output.WriteMessage(DungeonRaidInfo);
      }
      if (ErrCode != global::Zproto.EErrorCode.ErrSuccess) {
        output.WriteRawTag(192, 1);
        output.WriteEnum((int) ErrCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SceneUuid != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(SceneUuid);
      }
      if (flowInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(FlowInfo);
      }
      if (title_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Title);
      }
      if (target_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Target);
      }
      if (damage_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Damage);
      }
      if (vote_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Vote);
      }
      if (settlement_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Settlement);
      }
      if (dungeonPioneer_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(DungeonPioneer);
      }
      if (planetRoomInfo_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(PlanetRoomInfo);
      }
      if (dungeonVar_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(DungeonVar);
      }
      if (dungeonRank_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(DungeonRank);
      }
      if (dungeonAffixData_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(DungeonAffixData);
      }
      if (dungeonEvent_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(DungeonEvent);
      }
      if (dungeonScore_ != null) {
        output.WriteRawTag(114);
        output.WriteMessage(DungeonScore);
      }
      if (timerInfo_ != null) {
        output.WriteRawTag(122);
        output.WriteMessage(TimerInfo);
      }
      if (heroKey_ != null) {
        output.WriteRawTag(130, 1);
        output.WriteMessage(HeroKey);
      }
      if (dungeonUnionInfo_ != null) {
        output.WriteRawTag(138, 1);
        output.WriteMessage(DungeonUnionInfo);
      }
      if (dungeonPlayerList_ != null) {
        output.WriteRawTag(146, 1);
        output.WriteMessage(DungeonPlayerList);
      }
      if (reviveInfo_ != null) {
        output.WriteRawTag(154, 1);
        output.WriteMessage(ReviveInfo);
      }
      if (randomEntityConfigIdInfo_ != null) {
        output.WriteRawTag(162, 1);
        output.WriteMessage(RandomEntityConfigIdInfo);
      }
      if (dungeonSceneInfo_ != null) {
        output.WriteRawTag(170, 1);
        output.WriteMessage(DungeonSceneInfo);
      }
      if (dungeonVarAll_ != null) {
        output.WriteRawTag(178, 1);
        output.WriteMessage(DungeonVarAll);
      }
      if (dungeonRaidInfo_ != null) {
        output.WriteRawTag(186, 1);
        output.WriteMessage(DungeonRaidInfo);
      }
      if (ErrCode != global::Zproto.EErrorCode.ErrSuccess) {
        output.WriteRawTag(192, 1);
        output.WriteEnum((int) ErrCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SceneUuid != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SceneUuid);
      }
      if (flowInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FlowInfo);
      }
      if (title_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Title);
      }
      if (target_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Target);
      }
      if (damage_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Damage);
      }
      if (vote_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Vote);
      }
      if (settlement_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Settlement);
      }
      if (dungeonPioneer_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DungeonPioneer);
      }
      if (planetRoomInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlanetRoomInfo);
      }
      if (dungeonVar_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DungeonVar);
      }
      if (dungeonRank_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DungeonRank);
      }
      if (dungeonAffixData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DungeonAffixData);
      }
      if (dungeonEvent_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DungeonEvent);
      }
      if (dungeonScore_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DungeonScore);
      }
      if (timerInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TimerInfo);
      }
      if (heroKey_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(HeroKey);
      }
      if (dungeonUnionInfo_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(DungeonUnionInfo);
      }
      if (dungeonPlayerList_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(DungeonPlayerList);
      }
      if (reviveInfo_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(ReviveInfo);
      }
      if (randomEntityConfigIdInfo_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(RandomEntityConfigIdInfo);
      }
      if (dungeonSceneInfo_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(DungeonSceneInfo);
      }
      if (dungeonVarAll_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(DungeonVarAll);
      }
      if (dungeonRaidInfo_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(DungeonRaidInfo);
      }
      if (ErrCode != global::Zproto.EErrorCode.ErrSuccess) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) ErrCode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DungeonSyncData other) {
      if (other == null) {
        return;
      }
      if (other.SceneUuid != 0L) {
        SceneUuid = other.SceneUuid;
      }
      if (other.flowInfo_ != null) {
        if (flowInfo_ == null) {
          FlowInfo = new global::Zproto.DungeonFlowInfo();
        }
        FlowInfo.MergeFrom(other.FlowInfo);
      }
      if (other.title_ != null) {
        if (title_ == null) {
          Title = new global::Zproto.DungeonTitle();
        }
        Title.MergeFrom(other.Title);
      }
      if (other.target_ != null) {
        if (target_ == null) {
          Target = new global::Zproto.DungeonTarget();
        }
        Target.MergeFrom(other.Target);
      }
      if (other.damage_ != null) {
        if (damage_ == null) {
          Damage = new global::Zproto.DungeonDamage();
        }
        Damage.MergeFrom(other.Damage);
      }
      if (other.vote_ != null) {
        if (vote_ == null) {
          Vote = new global::Zproto.DungeonVote();
        }
        Vote.MergeFrom(other.Vote);
      }
      if (other.settlement_ != null) {
        if (settlement_ == null) {
          Settlement = new global::Zproto.DungeonSettlement();
        }
        Settlement.MergeFrom(other.Settlement);
      }
      if (other.dungeonPioneer_ != null) {
        if (dungeonPioneer_ == null) {
          DungeonPioneer = new global::Zproto.DungeonPioneer();
        }
        DungeonPioneer.MergeFrom(other.DungeonPioneer);
      }
      if (other.planetRoomInfo_ != null) {
        if (planetRoomInfo_ == null) {
          PlanetRoomInfo = new global::Zproto.DungeonPlanetMemoryRoom();
        }
        PlanetRoomInfo.MergeFrom(other.PlanetRoomInfo);
      }
      if (other.dungeonVar_ != null) {
        if (dungeonVar_ == null) {
          DungeonVar = new global::Zproto.DungeonVar();
        }
        DungeonVar.MergeFrom(other.DungeonVar);
      }
      if (other.dungeonRank_ != null) {
        if (dungeonRank_ == null) {
          DungeonRank = new global::Zproto.DungeonRankList();
        }
        DungeonRank.MergeFrom(other.DungeonRank);
      }
      if (other.dungeonAffixData_ != null) {
        if (dungeonAffixData_ == null) {
          DungeonAffixData = new global::Zproto.DungeonAffixData();
        }
        DungeonAffixData.MergeFrom(other.DungeonAffixData);
      }
      if (other.dungeonEvent_ != null) {
        if (dungeonEvent_ == null) {
          DungeonEvent = new global::Zproto.DungeonEvent();
        }
        DungeonEvent.MergeFrom(other.DungeonEvent);
      }
      if (other.dungeonScore_ != null) {
        if (dungeonScore_ == null) {
          DungeonScore = new global::Zproto.DungeonScore();
        }
        DungeonScore.MergeFrom(other.DungeonScore);
      }
      if (other.timerInfo_ != null) {
        if (timerInfo_ == null) {
          TimerInfo = new global::Zproto.DungeonTimerInfo();
        }
        TimerInfo.MergeFrom(other.TimerInfo);
      }
      if (other.heroKey_ != null) {
        if (heroKey_ == null) {
          HeroKey = new global::Zproto.DungeonHeroKeyInfo();
        }
        HeroKey.MergeFrom(other.HeroKey);
      }
      if (other.dungeonUnionInfo_ != null) {
        if (dungeonUnionInfo_ == null) {
          DungeonUnionInfo = new global::Zproto.DungeonUnionInfo();
        }
        DungeonUnionInfo.MergeFrom(other.DungeonUnionInfo);
      }
      if (other.dungeonPlayerList_ != null) {
        if (dungeonPlayerList_ == null) {
          DungeonPlayerList = new global::Zproto.DungeonPlayerList();
        }
        DungeonPlayerList.MergeFrom(other.DungeonPlayerList);
      }
      if (other.reviveInfo_ != null) {
        if (reviveInfo_ == null) {
          ReviveInfo = new global::Zproto.DungeonReviveInfo();
        }
        ReviveInfo.MergeFrom(other.ReviveInfo);
      }
      if (other.randomEntityConfigIdInfo_ != null) {
        if (randomEntityConfigIdInfo_ == null) {
          RandomEntityConfigIdInfo = new global::Zproto.DungeonRandomEntityConfigIdInfo();
        }
        RandomEntityConfigIdInfo.MergeFrom(other.RandomEntityConfigIdInfo);
      }
      if (other.dungeonSceneInfo_ != null) {
        if (dungeonSceneInfo_ == null) {
          DungeonSceneInfo = new global::Zproto.DungeonSceneInfo();
        }
        DungeonSceneInfo.MergeFrom(other.DungeonSceneInfo);
      }
      if (other.dungeonVarAll_ != null) {
        if (dungeonVarAll_ == null) {
          DungeonVarAll = new global::Zproto.DungeonVarAll();
        }
        DungeonVarAll.MergeFrom(other.DungeonVarAll);
      }
      if (other.dungeonRaidInfo_ != null) {
        if (dungeonRaidInfo_ == null) {
          DungeonRaidInfo = new global::Zproto.DungeonRaidInfo();
        }
        DungeonRaidInfo.MergeFrom(other.DungeonRaidInfo);
      }
      if (other.ErrCode != global::Zproto.EErrorCode.ErrSuccess) {
        ErrCode = other.ErrCode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SceneUuid = input.ReadInt64();
            break;
          }
          case 18: {
            if (flowInfo_ == null) {
              FlowInfo = new global::Zproto.DungeonFlowInfo();
            }
            input.ReadMessage(FlowInfo);
            break;
          }
          case 26: {
            if (title_ == null) {
              Title = new global::Zproto.DungeonTitle();
            }
            input.ReadMessage(Title);
            break;
          }
          case 34: {
            if (target_ == null) {
              Target = new global::Zproto.DungeonTarget();
            }
            input.ReadMessage(Target);
            break;
          }
          case 42: {
            if (damage_ == null) {
              Damage = new global::Zproto.DungeonDamage();
            }
            input.ReadMessage(Damage);
            break;
          }
          case 50: {
            if (vote_ == null) {
              Vote = new global::Zproto.DungeonVote();
            }
            input.ReadMessage(Vote);
            break;
          }
          case 58: {
            if (settlement_ == null) {
              Settlement = new global::Zproto.DungeonSettlement();
            }
            input.ReadMessage(Settlement);
            break;
          }
          case 66: {
            if (dungeonPioneer_ == null) {
              DungeonPioneer = new global::Zproto.DungeonPioneer();
            }
            input.ReadMessage(DungeonPioneer);
            break;
          }
          case 74: {
            if (planetRoomInfo_ == null) {
              PlanetRoomInfo = new global::Zproto.DungeonPlanetMemoryRoom();
            }
            input.ReadMessage(PlanetRoomInfo);
            break;
          }
          case 82: {
            if (dungeonVar_ == null) {
              DungeonVar = new global::Zproto.DungeonVar();
            }
            input.ReadMessage(DungeonVar);
            break;
          }
          case 90: {
            if (dungeonRank_ == null) {
              DungeonRank = new global::Zproto.DungeonRankList();
            }
            input.ReadMessage(DungeonRank);
            break;
          }
          case 98: {
            if (dungeonAffixData_ == null) {
              DungeonAffixData = new global::Zproto.DungeonAffixData();
            }
            input.ReadMessage(DungeonAffixData);
            break;
          }
          case 106: {
            if (dungeonEvent_ == null) {
              DungeonEvent = new global::Zproto.DungeonEvent();
            }
            input.ReadMessage(DungeonEvent);
            break;
          }
          case 114: {
            if (dungeonScore_ == null) {
              DungeonScore = new global::Zproto.DungeonScore();
            }
            input.ReadMessage(DungeonScore);
            break;
          }
          case 122: {
            if (timerInfo_ == null) {
              TimerInfo = new global::Zproto.DungeonTimerInfo();
            }
            input.ReadMessage(TimerInfo);
            break;
          }
          case 130: {
            if (heroKey_ == null) {
              HeroKey = new global::Zproto.DungeonHeroKeyInfo();
            }
            input.ReadMessage(HeroKey);
            break;
          }
          case 138: {
            if (dungeonUnionInfo_ == null) {
              DungeonUnionInfo = new global::Zproto.DungeonUnionInfo();
            }
            input.ReadMessage(DungeonUnionInfo);
            break;
          }
          case 146: {
            if (dungeonPlayerList_ == null) {
              DungeonPlayerList = new global::Zproto.DungeonPlayerList();
            }
            input.ReadMessage(DungeonPlayerList);
            break;
          }
          case 154: {
            if (reviveInfo_ == null) {
              ReviveInfo = new global::Zproto.DungeonReviveInfo();
            }
            input.ReadMessage(ReviveInfo);
            break;
          }
          case 162: {
            if (randomEntityConfigIdInfo_ == null) {
              RandomEntityConfigIdInfo = new global::Zproto.DungeonRandomEntityConfigIdInfo();
            }
            input.ReadMessage(RandomEntityConfigIdInfo);
            break;
          }
          case 170: {
            if (dungeonSceneInfo_ == null) {
              DungeonSceneInfo = new global::Zproto.DungeonSceneInfo();
            }
            input.ReadMessage(DungeonSceneInfo);
            break;
          }
          case 178: {
            if (dungeonVarAll_ == null) {
              DungeonVarAll = new global::Zproto.DungeonVarAll();
            }
            input.ReadMessage(DungeonVarAll);
            break;
          }
          case 186: {
            if (dungeonRaidInfo_ == null) {
              DungeonRaidInfo = new global::Zproto.DungeonRaidInfo();
            }
            input.ReadMessage(DungeonRaidInfo);
            break;
          }
          case 192: {
            ErrCode = (global::Zproto.EErrorCode) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SceneUuid = input.ReadInt64();
            break;
          }
          case 18: {
            if (flowInfo_ == null) {
              FlowInfo = new global::Zproto.DungeonFlowInfo();
            }
            input.ReadMessage(FlowInfo);
            break;
          }
          case 26: {
            if (title_ == null) {
              Title = new global::Zproto.DungeonTitle();
            }
            input.ReadMessage(Title);
            break;
          }
          case 34: {
            if (target_ == null) {
              Target = new global::Zproto.DungeonTarget();
            }
            input.ReadMessage(Target);
            break;
          }
          case 42: {
            if (damage_ == null) {
              Damage = new global::Zproto.DungeonDamage();
            }
            input.ReadMessage(Damage);
            break;
          }
          case 50: {
            if (vote_ == null) {
              Vote = new global::Zproto.DungeonVote();
            }
            input.ReadMessage(Vote);
            break;
          }
          case 58: {
            if (settlement_ == null) {
              Settlement = new global::Zproto.DungeonSettlement();
            }
            input.ReadMessage(Settlement);
            break;
          }
          case 66: {
            if (dungeonPioneer_ == null) {
              DungeonPioneer = new global::Zproto.DungeonPioneer();
            }
            input.ReadMessage(DungeonPioneer);
            break;
          }
          case 74: {
            if (planetRoomInfo_ == null) {
              PlanetRoomInfo = new global::Zproto.DungeonPlanetMemoryRoom();
            }
            input.ReadMessage(PlanetRoomInfo);
            break;
          }
          case 82: {
            if (dungeonVar_ == null) {
              DungeonVar = new global::Zproto.DungeonVar();
            }
            input.ReadMessage(DungeonVar);
            break;
          }
          case 90: {
            if (dungeonRank_ == null) {
              DungeonRank = new global::Zproto.DungeonRankList();
            }
            input.ReadMessage(DungeonRank);
            break;
          }
          case 98: {
            if (dungeonAffixData_ == null) {
              DungeonAffixData = new global::Zproto.DungeonAffixData();
            }
            input.ReadMessage(DungeonAffixData);
            break;
          }
          case 106: {
            if (dungeonEvent_ == null) {
              DungeonEvent = new global::Zproto.DungeonEvent();
            }
            input.ReadMessage(DungeonEvent);
            break;
          }
          case 114: {
            if (dungeonScore_ == null) {
              DungeonScore = new global::Zproto.DungeonScore();
            }
            input.ReadMessage(DungeonScore);
            break;
          }
          case 122: {
            if (timerInfo_ == null) {
              TimerInfo = new global::Zproto.DungeonTimerInfo();
            }
            input.ReadMessage(TimerInfo);
            break;
          }
          case 130: {
            if (heroKey_ == null) {
              HeroKey = new global::Zproto.DungeonHeroKeyInfo();
            }
            input.ReadMessage(HeroKey);
            break;
          }
          case 138: {
            if (dungeonUnionInfo_ == null) {
              DungeonUnionInfo = new global::Zproto.DungeonUnionInfo();
            }
            input.ReadMessage(DungeonUnionInfo);
            break;
          }
          case 146: {
            if (dungeonPlayerList_ == null) {
              DungeonPlayerList = new global::Zproto.DungeonPlayerList();
            }
            input.ReadMessage(DungeonPlayerList);
            break;
          }
          case 154: {
            if (reviveInfo_ == null) {
              ReviveInfo = new global::Zproto.DungeonReviveInfo();
            }
            input.ReadMessage(ReviveInfo);
            break;
          }
          case 162: {
            if (randomEntityConfigIdInfo_ == null) {
              RandomEntityConfigIdInfo = new global::Zproto.DungeonRandomEntityConfigIdInfo();
            }
            input.ReadMessage(RandomEntityConfigIdInfo);
            break;
          }
          case 170: {
            if (dungeonSceneInfo_ == null) {
              DungeonSceneInfo = new global::Zproto.DungeonSceneInfo();
            }
            input.ReadMessage(DungeonSceneInfo);
            break;
          }
          case 178: {
            if (dungeonVarAll_ == null) {
              DungeonVarAll = new global::Zproto.DungeonVarAll();
            }
            input.ReadMessage(DungeonVarAll);
            break;
          }
          case 186: {
            if (dungeonRaidInfo_ == null) {
              DungeonRaidInfo = new global::Zproto.DungeonRaidInfo();
            }
            input.ReadMessage(DungeonRaidInfo);
            break;
          }
          case 192: {
            ErrCode = (global::Zproto.EErrorCode) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
