// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_notify_join_team_request.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_notify_join_team_request.proto</summary>
  public static partial class StruNotifyJoinTeamRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_notify_join_team_request.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruNotifyJoinTeamRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNzdHJ1X25vdGlmeV9qb2luX3RlYW1fcmVxdWVzdC5wcm90bxIGenByb3Rv",
            "GhtlbnVtX2VfdGVhbV9qb2luX3R5cGUucHJvdG8aGXN0cnVfdGVhbV9iYXNl",
            "X2luZm8ucHJvdG8aGHN0cnVfdGVhbV9tZW1fZGF0YS5wcm90bxooc3RydV90",
            "ZWFtX21lbV9yZWFsX3RpbWVfdm9pY2VfaW5mby5wcm90byLWAgoVTm90aWZ5",
            "Sm9pblRlYW1SZXF1ZXN0EicKCWJhc2VfaW5mbxgBIAEoCzIULnpwcm90by5U",
            "ZWFtQmFzZUluZm8SKAoLbWVtYmVyX2RhdGEYAiADKAsyEy56cHJvdG8uVGVh",
            "bU1lbURhdGESWwoZbWVtX3JlYWxfdGltZV92b2ljZV9pbmZvcxgEIAMoCzI4",
            "Lnpwcm90by5Ob3RpZnlKb2luVGVhbVJlcXVlc3QuTWVtUmVhbFRpbWVWb2lj",
            "ZUluZm9zRW50cnkSLQoOdGVhbV9qb2luX3R5cGUYBSABKA4yFS56cHJvdG8u",
            "RVRlYW1Kb2luVHlwZRpeChpNZW1SZWFsVGltZVZvaWNlSW5mb3NFbnRyeRIL",
            "CgNrZXkYASABKAMSLwoFdmFsdWUYAiABKAsyIC56cHJvdG8uVGVhbU1lbVJl",
            "YWxUaW1lVm9pY2VJbmZvOgI4AWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.EnumETeamJoinTypeReflection.Descriptor, global::Zproto.StruTeamBaseInfoReflection.Descriptor, global::Zproto.StruTeamMemDataReflection.Descriptor, global::Zproto.StruTeamMemRealTimeVoiceInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.NotifyJoinTeamRequest), global::Zproto.NotifyJoinTeamRequest.Parser, new[]{ "BaseInfo", "MemberData", "MemRealTimeVoiceInfos", "TeamJoinType" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class NotifyJoinTeamRequest : pb::IMessage<NotifyJoinTeamRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NotifyJoinTeamRequest> _parser = new pb::MessageParser<NotifyJoinTeamRequest>(() => new NotifyJoinTeamRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NotifyJoinTeamRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruNotifyJoinTeamRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NotifyJoinTeamRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NotifyJoinTeamRequest(NotifyJoinTeamRequest other) : this() {
      baseInfo_ = other.baseInfo_ != null ? other.baseInfo_.Clone() : null;
      memberData_ = other.memberData_.Clone();
      memRealTimeVoiceInfos_ = other.memRealTimeVoiceInfos_.Clone();
      teamJoinType_ = other.teamJoinType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NotifyJoinTeamRequest Clone() {
      return new NotifyJoinTeamRequest(this);
    }

    /// <summary>Field number for the "base_info" field.</summary>
    public const int BaseInfoFieldNumber = 1;
    private global::Zproto.TeamBaseInfo baseInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.TeamBaseInfo BaseInfo {
      get { return baseInfo_; }
      set {
        baseInfo_ = value;
      }
    }

    /// <summary>Field number for the "member_data" field.</summary>
    public const int MemberDataFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Zproto.TeamMemData> _repeated_memberData_codec
        = pb::FieldCodec.ForMessage(18, global::Zproto.TeamMemData.Parser);
    private readonly pbc::RepeatedField<global::Zproto.TeamMemData> memberData_ = new pbc::RepeatedField<global::Zproto.TeamMemData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Zproto.TeamMemData> MemberData {
      get { return memberData_; }
    }

    /// <summary>Field number for the "mem_real_time_voice_infos" field.</summary>
    public const int MemRealTimeVoiceInfosFieldNumber = 4;
    private static readonly pbc::MapField<long, global::Zproto.TeamMemRealTimeVoiceInfo>.Codec _map_memRealTimeVoiceInfos_codec
        = new pbc::MapField<long, global::Zproto.TeamMemRealTimeVoiceInfo>.Codec(pb::FieldCodec.ForInt64(8, 0L), pb::FieldCodec.ForMessage(18, global::Zproto.TeamMemRealTimeVoiceInfo.Parser), 34);
    private readonly pbc::MapField<long, global::Zproto.TeamMemRealTimeVoiceInfo> memRealTimeVoiceInfos_ = new pbc::MapField<long, global::Zproto.TeamMemRealTimeVoiceInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<long, global::Zproto.TeamMemRealTimeVoiceInfo> MemRealTimeVoiceInfos {
      get { return memRealTimeVoiceInfos_; }
    }

    /// <summary>Field number for the "team_join_type" field.</summary>
    public const int TeamJoinTypeFieldNumber = 5;
    private global::Zproto.ETeamJoinType teamJoinType_ = global::Zproto.ETeamJoinType.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.ETeamJoinType TeamJoinType {
      get { return teamJoinType_; }
      set {
        teamJoinType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NotifyJoinTeamRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NotifyJoinTeamRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(BaseInfo, other.BaseInfo)) return false;
      if(!memberData_.Equals(other.memberData_)) return false;
      if (!MemRealTimeVoiceInfos.Equals(other.MemRealTimeVoiceInfos)) return false;
      if (TeamJoinType != other.TeamJoinType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (baseInfo_ != null) hash ^= BaseInfo.GetHashCode();
      hash ^= memberData_.GetHashCode();
      hash ^= MemRealTimeVoiceInfos.GetHashCode();
      if (TeamJoinType != global::Zproto.ETeamJoinType.None) hash ^= TeamJoinType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (baseInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(BaseInfo);
      }
      memberData_.WriteTo(output, _repeated_memberData_codec);
      memRealTimeVoiceInfos_.WriteTo(output, _map_memRealTimeVoiceInfos_codec);
      if (TeamJoinType != global::Zproto.ETeamJoinType.None) {
        output.WriteRawTag(40);
        output.WriteEnum((int) TeamJoinType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (baseInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(BaseInfo);
      }
      memberData_.WriteTo(ref output, _repeated_memberData_codec);
      memRealTimeVoiceInfos_.WriteTo(ref output, _map_memRealTimeVoiceInfos_codec);
      if (TeamJoinType != global::Zproto.ETeamJoinType.None) {
        output.WriteRawTag(40);
        output.WriteEnum((int) TeamJoinType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (baseInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BaseInfo);
      }
      size += memberData_.CalculateSize(_repeated_memberData_codec);
      size += memRealTimeVoiceInfos_.CalculateSize(_map_memRealTimeVoiceInfos_codec);
      if (TeamJoinType != global::Zproto.ETeamJoinType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TeamJoinType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NotifyJoinTeamRequest other) {
      if (other == null) {
        return;
      }
      if (other.baseInfo_ != null) {
        if (baseInfo_ == null) {
          BaseInfo = new global::Zproto.TeamBaseInfo();
        }
        BaseInfo.MergeFrom(other.BaseInfo);
      }
      memberData_.Add(other.memberData_);
      memRealTimeVoiceInfos_.MergeFrom(other.memRealTimeVoiceInfos_);
      if (other.TeamJoinType != global::Zproto.ETeamJoinType.None) {
        TeamJoinType = other.TeamJoinType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (baseInfo_ == null) {
              BaseInfo = new global::Zproto.TeamBaseInfo();
            }
            input.ReadMessage(BaseInfo);
            break;
          }
          case 18: {
            memberData_.AddEntriesFrom(input, _repeated_memberData_codec);
            break;
          }
          case 34: {
            memRealTimeVoiceInfos_.AddEntriesFrom(input, _map_memRealTimeVoiceInfos_codec);
            break;
          }
          case 40: {
            TeamJoinType = (global::Zproto.ETeamJoinType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (baseInfo_ == null) {
              BaseInfo = new global::Zproto.TeamBaseInfo();
            }
            input.ReadMessage(BaseInfo);
            break;
          }
          case 18: {
            memberData_.AddEntriesFrom(ref input, _repeated_memberData_codec);
            break;
          }
          case 34: {
            memRealTimeVoiceInfos_.AddEntriesFrom(ref input, _map_memRealTimeVoiceInfos_codec);
            break;
          }
          case 40: {
            TeamJoinType = (global::Zproto.ETeamJoinType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
