// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_get_union_activity_info_reply.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_get_union_activity_info_reply.proto</summary>
  public static partial class StruGetUnionActivityInfoReplyReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_get_union_activity_info_reply.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruGetUnionActivityInfoReplyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CihzdHJ1X2dldF91bmlvbl9hY3Rpdml0eV9pbmZvX3JlcGx5LnByb3RvEgZ6",
            "cHJvdG8aF2VudW1fZV9lcnJvcl9jb2RlLnByb3RvGh1zdHJ1X21lbV91bmlv",
            "bl9hY3Rpdml0eS5wcm90bxoZc3RydV91bmlvbl9hY3Rpdml0eS5wcm90byKh",
            "AQoZR2V0VW5pb25BY3Rpdml0eUluZm9SZXBseRItCg51bmlvbl9hY3Rpdml0",
            "eRgBIAEoCzIVLnpwcm90by5VbmlvbkFjdGl2aXR5Ei8KDXNlbGZfYWN0aXZp",
            "dHkYAiABKAsyGC56cHJvdG8uTWVtVW5pb25BY3Rpdml0eRIkCghlcnJfY29k",
            "ZRgDIAEoDjISLnpwcm90by5FRXJyb3JDb2RlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.EnumEErrorCodeReflection.Descriptor, global::Zproto.StruMemUnionActivityReflection.Descriptor, global::Zproto.StruUnionActivityReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.GetUnionActivityInfoReply), global::Zproto.GetUnionActivityInfoReply.Parser, new[]{ "UnionActivity", "SelfActivity", "ErrCode" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetUnionActivityInfoReply : pb::IMessage<GetUnionActivityInfoReply>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetUnionActivityInfoReply> _parser = new pb::MessageParser<GetUnionActivityInfoReply>(() => new GetUnionActivityInfoReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetUnionActivityInfoReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruGetUnionActivityInfoReplyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetUnionActivityInfoReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetUnionActivityInfoReply(GetUnionActivityInfoReply other) : this() {
      unionActivity_ = other.unionActivity_ != null ? other.unionActivity_.Clone() : null;
      selfActivity_ = other.selfActivity_ != null ? other.selfActivity_.Clone() : null;
      errCode_ = other.errCode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetUnionActivityInfoReply Clone() {
      return new GetUnionActivityInfoReply(this);
    }

    /// <summary>Field number for the "union_activity" field.</summary>
    public const int UnionActivityFieldNumber = 1;
    private global::Zproto.UnionActivity unionActivity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.UnionActivity UnionActivity {
      get { return unionActivity_; }
      set {
        unionActivity_ = value;
      }
    }

    /// <summary>Field number for the "self_activity" field.</summary>
    public const int SelfActivityFieldNumber = 2;
    private global::Zproto.MemUnionActivity selfActivity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.MemUnionActivity SelfActivity {
      get { return selfActivity_; }
      set {
        selfActivity_ = value;
      }
    }

    /// <summary>Field number for the "err_code" field.</summary>
    public const int ErrCodeFieldNumber = 3;
    private global::Zproto.EErrorCode errCode_ = global::Zproto.EErrorCode.ErrSuccess;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.EErrorCode ErrCode {
      get { return errCode_; }
      set {
        errCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetUnionActivityInfoReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetUnionActivityInfoReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(UnionActivity, other.UnionActivity)) return false;
      if (!object.Equals(SelfActivity, other.SelfActivity)) return false;
      if (ErrCode != other.ErrCode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (unionActivity_ != null) hash ^= UnionActivity.GetHashCode();
      if (selfActivity_ != null) hash ^= SelfActivity.GetHashCode();
      if (ErrCode != global::Zproto.EErrorCode.ErrSuccess) hash ^= ErrCode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (unionActivity_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(UnionActivity);
      }
      if (selfActivity_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(SelfActivity);
      }
      if (ErrCode != global::Zproto.EErrorCode.ErrSuccess) {
        output.WriteRawTag(24);
        output.WriteEnum((int) ErrCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (unionActivity_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(UnionActivity);
      }
      if (selfActivity_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(SelfActivity);
      }
      if (ErrCode != global::Zproto.EErrorCode.ErrSuccess) {
        output.WriteRawTag(24);
        output.WriteEnum((int) ErrCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (unionActivity_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UnionActivity);
      }
      if (selfActivity_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SelfActivity);
      }
      if (ErrCode != global::Zproto.EErrorCode.ErrSuccess) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ErrCode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetUnionActivityInfoReply other) {
      if (other == null) {
        return;
      }
      if (other.unionActivity_ != null) {
        if (unionActivity_ == null) {
          UnionActivity = new global::Zproto.UnionActivity();
        }
        UnionActivity.MergeFrom(other.UnionActivity);
      }
      if (other.selfActivity_ != null) {
        if (selfActivity_ == null) {
          SelfActivity = new global::Zproto.MemUnionActivity();
        }
        SelfActivity.MergeFrom(other.SelfActivity);
      }
      if (other.ErrCode != global::Zproto.EErrorCode.ErrSuccess) {
        ErrCode = other.ErrCode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (unionActivity_ == null) {
              UnionActivity = new global::Zproto.UnionActivity();
            }
            input.ReadMessage(UnionActivity);
            break;
          }
          case 18: {
            if (selfActivity_ == null) {
              SelfActivity = new global::Zproto.MemUnionActivity();
            }
            input.ReadMessage(SelfActivity);
            break;
          }
          case 24: {
            ErrCode = (global::Zproto.EErrorCode) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (unionActivity_ == null) {
              UnionActivity = new global::Zproto.UnionActivity();
            }
            input.ReadMessage(UnionActivity);
            break;
          }
          case 18: {
            if (selfActivity_ == null) {
              SelfActivity = new global::Zproto.MemUnionActivity();
            }
            input.ReadMessage(SelfActivity);
            break;
          }
          case 24: {
            ErrCode = (global::Zproto.EErrorCode) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
