// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_send_sys_chat_hypertext_request.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_send_sys_chat_hypertext_request.proto</summary>
  public static partial class StruSendSysChatHypertextRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_send_sys_chat_hypertext_request.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruSendSysChatHypertextRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CipzdHJ1X3NlbmRfc3lzX2NoYXRfaHlwZXJ0ZXh0X3JlcXVlc3QucHJvdG8S",
            "Bnpwcm90bxoZc3RydV9jaGF0X2h5cGVydGV4dC5wcm90bxohZW51bV9jaGl0",
            "X2NoYXRfY2hhbm5lbF90eXBlLnByb3RvIsoBChtTZW5kU3lzQ2hhdEh5cGVy",
            "dGV4dFJlcXVlc3QSMQoMY2hhbm5lbF90eXBlGAEgASgOMhsuenByb3RvLkNo",
            "aXRDaGF0Q2hhbm5lbFR5cGUSKAoJaHlwZXJ0ZXh0GAIgASgLMhUuenByb3Rv",
            "LkNoYXRIeXBlcnRleHQSFgoOdGFyZ2V0X2NoYXJfaWQYAyABKAMSFAoMc2Vu",
            "ZF9jaGFyX2lkGAQgASgDEgwKBHRleHQYBSABKAkSEgoKc2VuZF90b19tZRgG",
            "IAEoCGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruChatHypertextReflection.Descriptor, global::Zproto.EnumChitChatChannelTypeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.SendSysChatHypertextRequest), global::Zproto.SendSysChatHypertextRequest.Parser, new[]{ "ChannelType", "Hypertext", "TargetCharId", "SendCharId", "Text", "SendToMe" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SendSysChatHypertextRequest : pb::IMessage<SendSysChatHypertextRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SendSysChatHypertextRequest> _parser = new pb::MessageParser<SendSysChatHypertextRequest>(() => new SendSysChatHypertextRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SendSysChatHypertextRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruSendSysChatHypertextRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SendSysChatHypertextRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SendSysChatHypertextRequest(SendSysChatHypertextRequest other) : this() {
      channelType_ = other.channelType_;
      hypertext_ = other.hypertext_ != null ? other.hypertext_.Clone() : null;
      targetCharId_ = other.targetCharId_;
      sendCharId_ = other.sendCharId_;
      text_ = other.text_;
      sendToMe_ = other.sendToMe_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SendSysChatHypertextRequest Clone() {
      return new SendSysChatHypertextRequest(this);
    }

    /// <summary>Field number for the "channel_type" field.</summary>
    public const int ChannelTypeFieldNumber = 1;
    private global::Zproto.ChitChatChannelType channelType_ = global::Zproto.ChitChatChannelType.ChannelNull;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.ChitChatChannelType ChannelType {
      get { return channelType_; }
      set {
        channelType_ = value;
      }
    }

    /// <summary>Field number for the "hypertext" field.</summary>
    public const int HypertextFieldNumber = 2;
    private global::Zproto.ChatHypertext hypertext_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.ChatHypertext Hypertext {
      get { return hypertext_; }
      set {
        hypertext_ = value;
      }
    }

    /// <summary>Field number for the "target_char_id" field.</summary>
    public const int TargetCharIdFieldNumber = 3;
    private long targetCharId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TargetCharId {
      get { return targetCharId_; }
      set {
        targetCharId_ = value;
      }
    }

    /// <summary>Field number for the "send_char_id" field.</summary>
    public const int SendCharIdFieldNumber = 4;
    private long sendCharId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SendCharId {
      get { return sendCharId_; }
      set {
        sendCharId_ = value;
      }
    }

    /// <summary>Field number for the "text" field.</summary>
    public const int TextFieldNumber = 5;
    private string text_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Text {
      get { return text_; }
      set {
        text_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "send_to_me" field.</summary>
    public const int SendToMeFieldNumber = 6;
    private bool sendToMe_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool SendToMe {
      get { return sendToMe_; }
      set {
        sendToMe_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SendSysChatHypertextRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SendSysChatHypertextRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ChannelType != other.ChannelType) return false;
      if (!object.Equals(Hypertext, other.Hypertext)) return false;
      if (TargetCharId != other.TargetCharId) return false;
      if (SendCharId != other.SendCharId) return false;
      if (Text != other.Text) return false;
      if (SendToMe != other.SendToMe) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ChannelType != global::Zproto.ChitChatChannelType.ChannelNull) hash ^= ChannelType.GetHashCode();
      if (hypertext_ != null) hash ^= Hypertext.GetHashCode();
      if (TargetCharId != 0L) hash ^= TargetCharId.GetHashCode();
      if (SendCharId != 0L) hash ^= SendCharId.GetHashCode();
      if (Text.Length != 0) hash ^= Text.GetHashCode();
      if (SendToMe != false) hash ^= SendToMe.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ChannelType != global::Zproto.ChitChatChannelType.ChannelNull) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ChannelType);
      }
      if (hypertext_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Hypertext);
      }
      if (TargetCharId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TargetCharId);
      }
      if (SendCharId != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(SendCharId);
      }
      if (Text.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Text);
      }
      if (SendToMe != false) {
        output.WriteRawTag(48);
        output.WriteBool(SendToMe);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ChannelType != global::Zproto.ChitChatChannelType.ChannelNull) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ChannelType);
      }
      if (hypertext_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Hypertext);
      }
      if (TargetCharId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TargetCharId);
      }
      if (SendCharId != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(SendCharId);
      }
      if (Text.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Text);
      }
      if (SendToMe != false) {
        output.WriteRawTag(48);
        output.WriteBool(SendToMe);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ChannelType != global::Zproto.ChitChatChannelType.ChannelNull) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ChannelType);
      }
      if (hypertext_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Hypertext);
      }
      if (TargetCharId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TargetCharId);
      }
      if (SendCharId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SendCharId);
      }
      if (Text.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Text);
      }
      if (SendToMe != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SendSysChatHypertextRequest other) {
      if (other == null) {
        return;
      }
      if (other.ChannelType != global::Zproto.ChitChatChannelType.ChannelNull) {
        ChannelType = other.ChannelType;
      }
      if (other.hypertext_ != null) {
        if (hypertext_ == null) {
          Hypertext = new global::Zproto.ChatHypertext();
        }
        Hypertext.MergeFrom(other.Hypertext);
      }
      if (other.TargetCharId != 0L) {
        TargetCharId = other.TargetCharId;
      }
      if (other.SendCharId != 0L) {
        SendCharId = other.SendCharId;
      }
      if (other.Text.Length != 0) {
        Text = other.Text;
      }
      if (other.SendToMe != false) {
        SendToMe = other.SendToMe;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ChannelType = (global::Zproto.ChitChatChannelType) input.ReadEnum();
            break;
          }
          case 18: {
            if (hypertext_ == null) {
              Hypertext = new global::Zproto.ChatHypertext();
            }
            input.ReadMessage(Hypertext);
            break;
          }
          case 24: {
            TargetCharId = input.ReadInt64();
            break;
          }
          case 32: {
            SendCharId = input.ReadInt64();
            break;
          }
          case 42: {
            Text = input.ReadString();
            break;
          }
          case 48: {
            SendToMe = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ChannelType = (global::Zproto.ChitChatChannelType) input.ReadEnum();
            break;
          }
          case 18: {
            if (hypertext_ == null) {
              Hypertext = new global::Zproto.ChatHypertext();
            }
            input.ReadMessage(Hypertext);
            break;
          }
          case 24: {
            TargetCharId = input.ReadInt64();
            break;
          }
          case 32: {
            SendCharId = input.ReadInt64();
            break;
          }
          case 42: {
            Text = input.ReadString();
            break;
          }
          case 48: {
            SendToMe = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
